extends Node
## Global signal hub. Systems communicate via these signals instead of direct references.

signal notify(text: String, kind: String) # kind: info, warn, danger, good, quest
signal weather_changed(kind: String)
signal inventory_changed()
signal equipment_changed()
signal item_picked(id: String, count: int)
signal creature_killed(species: String, by_player: bool, pos: Vector3, data: Dictionary)
signal creature_tamed(uid: int)
signal creature_died(uid: int)
signal creature_born(uid: int)
signal player_died()
signal player_damaged(amount: float)
signal player_level_up(level: int)
signal quest_updated(qid: String)
signal quest_completed(qid: String)
signal research_completed(rid: String)
signal crafted(item_id: String, count: int)
signal built(kind: String, pos: Vector3)
signal faction_changed(fid: String, rep: int)
signal dialogue_started(npc_id: String)
signal location_discovered(poi_id: String)
signal region_entered(region_id: String)
signal interacted(target_id: String)
signal demon_unlocked()
signal form_changed(demon: bool)
signal party_changed()
signal hud_refresh()
signal game_saved(slot: String)
signal game_loaded()
signal lexicon_updated(species: String)
signal time_skipped(hours: float)
signal ui_opened(name: String)
signal ui_closed(name: String)
