# Items. cat: material, food, consumable, weapon, armor, ammo, tool, trap, rune, essence, quest, saddle, special
# Material properties (mat) feed the modular crafting system.

def M(name, w=0.5, v=1, desc="", **kw):
    d = dict(name=name, cat="material", weight=w, stack=100, value=v, desc=desc)
    d.update(kw)
    return d


ELEMENTS_LIST = ["fire", "water", "ice", "lightning", "earth", "wind", "nature", "poison", "light", "shadow", "blood"]
EL_DE = {"fire": "Feuer", "water": "Wasser", "ice": "Eis", "lightning": "Blitz", "earth": "Erde", "wind": "Wind",
         "nature": "Natur", "poison": "Gift", "light": "Licht", "shadow": "Schatten", "blood": "Blut"}

ITEMS = {
    # ---------------------------------------------------------------- basic materials
    "wood": M("Holz", 0.8, 1, "Grundmaterial für Werkzeuge und Bauten.", mat=dict(tags=["shaft", "wood"], dmg=1.0, tier=1)),
    "hardwood": M("Hartholz", 1.0, 3, "Dichtes Holz aus alten Dschungelbäumen.", mat=dict(tags=["shaft", "wood"], dmg=1.1, tier=2)),
    "stone": M("Stein", 1.0, 1, "Überall zu finden.", mat=dict(tags=["head", "stone"], dmg=1.0, tier=1)),
    "flint": M("Feuerstein", 0.5, 2, "Scharfkantiger Stein für Klingen und Spitzen.", mat=dict(tags=["head", "stone"], dmg=1.2, tier=1)),
    "fiber": M("Fasern", 0.1, 1, "Aus Büschen und Gräsern.", mat=dict(tags=["binding"], dmg=1.0, tier=1)),
    "hide": M("Rohhaut", 0.6, 2, "Von fast allen Tieren."),
    "leather": M("Leder", 0.5, 4, "Gegerbte Haut.", mat=dict(tags=["binding", "padding"], dmg=1.05, tier=2)),
    "pelt": M("Fell", 0.8, 5, "Warm – schützt vor Kälte."),
    "bone": M("Knochen", 0.5, 2, "", mat=dict(tags=["head"], dmg=1.1, tier=1)),
    "large_bone": M("Großer Knochen", 2.0, 6, "Von großen Bestien.", mat=dict(tags=["head", "shaft"], dmg=1.25, tier=2)),
    "sinew": M("Sehne", 0.1, 3, "Zähes Bindematerial.", mat=dict(tags=["binding"], dmg=1.1, tier=2)),
    "silk": M("Spinnenseide", 0.1, 8, "Extrem reißfest.", mat=dict(tags=["binding", "padding"], dmg=1.2, tier=3)),
    "feather": M("Feder", 0.05, 2, "Für Pfeile und Zierde."),
    "scales": M("Schuppen", 0.4, 6, "Leichte Panzerung.", mat=dict(tags=["plating"], dmg=1.0, tier=2, armor=1.2)),
    "keratin_plate": M("Hornplatte", 1.0, 10, "Panzerplatten großer Pflanzenfresser.", mat=dict(tags=["plating"], dmg=1.0, tier=2, armor=1.5)),
    "horn": M("Horn", 1.0, 10, "", mat=dict(tags=["head"], dmg=1.35, tier=2)),
    "chitin": M("Chitin", 0.5, 8, "Panzer von Gliederfüßern.", mat=dict(tags=["plating"], dmg=1.0, tier=3, armor=1.6)),
    "metal_ore": M("Metallerz", 1.5, 6, "Wird in der Schmiede geschmolzen."),
    "metal_ingot": M("Metallbarren", 1.0, 15, "", mat=dict(tags=["head", "plating"], dmg=1.6, tier=3, armor=2.0)),
    "obsidian": M("Obsidian", 0.8, 12, "Vulkanglas – rasiermesserscharf.", mat=dict(tags=["head"], dmg=1.75, tier=3)),
    "crystal": M("Kristall", 0.3, 15, "Leitet magische Energie.", mat=dict(tags=["focus"], dmg=1.3, tier=3)),
    "sulfur": M("Schwefel", 0.3, 5, ""),
    "salt": M("Salz", 0.2, 3, ""),
    "clay": M("Lehm", 1.0, 2, ""),
    "charcoal": M("Holzkohle", 0.2, 2, ""),
    "cement": M("Mörtel", 1.0, 4, "Für Steinbauten."),
    "gunpowder": M("Schwarzpulver", 0.1, 10, "Explosiv."),
    "thatch": M("Stroh", 0.3, 1, "Aus Fasern und Schilf."),
    "sail_membrane": M("Segelhaut", 1.0, 20, "Flexibel und hitzebeständig."),
    "venom_gland": M("Giftdrüse", 0.2, 12, ""),
    "raptor_claw": M("Raptorklaue", 0.2, 10, "Trophäe und Klingenmaterial.", mat=dict(tags=["head"], dmg=1.45, tier=2)),
    "trex_tooth": M("Tyrannenzahn", 0.3, 40, "Begehrte Trophäe.", mat=dict(tags=["head"], dmg=1.8, tier=3)),
    "saber_fang": M("Säbelzahn", 0.3, 30, "", mat=dict(tags=["head"], dmg=1.6, tier=3)),
    "ivory": M("Elfenbein", 2.0, 40, ""),
    "shark_tooth": M("Haizahn", 0.1, 12, "", mat=dict(tags=["head"], dmg=1.5, tier=2)),
    "wyvern_scale": M("Wyvernschuppe", 0.5, 45, "", mat=dict(tags=["plating"], dmg=1.0, tier=4, armor=2.6)),
    "charred_bone": M("Verkohlter Knochen", 0.5, 8, ""),
    "berries": dict(name="Beeren", cat="food", weight=0.05, stack=100, value=1, food=6, desc="Essbar. Pflanzenfresser lieben sie."),
    "veggies": dict(name="Wurzelknollen", cat="food", weight=0.2, stack=50, value=2, food=10, desc="Nahrhaft für Mensch und Tier."),
    "narcoberry": dict(name="Schlafbeere", cat="material", weight=0.05, stack=100, value=2, desc="Leicht betäubend."),
    "rare_flower": dict(name="Seltene Blüte", cat="material", weight=0.05, stack=50, value=8, desc="Lockt scheue Pflanzenfresser an."),
    "herb_healing": dict(name="Heilkraut", cat="consumable", weight=0.05, stack=50, value=3, heal=12, desc="Lindert kleine Wunden."),
    "mushroom": dict(name="Pilz", cat="material", weight=0.1, stack=50, value=3, desc="Zutat für Alchemie."),
    "raw_meat": dict(name="Rohes Fleisch", cat="food", weight=0.3, stack=40, value=2, food=8, sick=0.25, spoil=True, desc="Besser gebraten. Raubtiere fressen es gern."),
    "raw_prime_meat": dict(name="Edles rohes Fleisch", cat="food", weight=0.4, stack=40, value=6, food=12, sick=0.25, desc="Großraubtiere bevorzugen es."),
    "raw_fish": dict(name="Roher Fisch", cat="food", weight=0.2, stack=40, value=2, food=7, sick=0.15),
    "raw_prime_fish": dict(name="Edler roher Fisch", cat="food", weight=0.3, stack=40, value=6, food=11, sick=0.15),
    "cooked_meat": dict(name="Gebratenes Fleisch", cat="food", weight=0.25, stack=40, value=4, food=25, desc="Sättigt gut."),
    "cooked_prime": dict(name="Gebratenes Edelfleisch", cat="food", weight=0.3, stack=40, value=10, food=35, buff="stark", desc="Sättigt sehr gut und stärkt."),
    "cooked_fish": dict(name="Gebratener Fisch", cat="food", weight=0.2, stack=40, value=4, food=22),
    "jerky": dict(name="Trockenfleisch", cat="food", weight=0.15, stack=60, value=8, food=30, desc="Haltbare Reiseverpflegung."),
    "stew": dict(name="Jägereintopf", cat="food", weight=0.5, stack=20, value=15, food=50, buff="satt", desc="Lange satt, erhöhte Ausdauer-Regeneration."),
    "kibble": dict(name="Bestienfutter", cat="food", weight=0.2, stack=40, value=12, food=15, tame_bonus=2.0, desc="Von allen zähmbaren Kreaturen geschätzt; beschleunigt die Zähmung stark."),
    "wyvern_milk": dict(name="Wyvernmilch", cat="food", weight=0.3, stack=10, value=60, food=20, desc="Einzige Nahrung junger Wyvern."),
    # ---------------------------------------------------------------- consumables
    "bandage": dict(name="Verband", cat="consumable", weight=0.1, stack=20, value=4, heal=25, desc="Stoppt Blutungen, heilt 25 LP."),
    "healing_salve": dict(name="Heilsalbe", cat="consumable", weight=0.1, stack=20, value=10, heal=50, desc="Heilt 50 LP über Zeit."),
    "healing_potion": dict(name="Heiltrank", cat="consumable", weight=0.2, stack=10, value=25, heal=100, desc="Heilt 100 LP sofort."),
    "stamina_tonic": dict(name="Ausdauertonikum", cat="consumable", weight=0.2, stack=10, value=15, buff="ausdauer", desc="Ausdauer regeneriert 60 s doppelt."),
    "narcotic": dict(name="Betäubungsmittel", cat="consumable", weight=0.1, stack=50, value=6, torpor_feed=40, desc="Hält eine betäubte Kreatur länger bewusstlos (verfüttern)."),
    "antidote": dict(name="Gegengift", cat="consumable", weight=0.1, stack=20, value=10, cure="poison", desc="Heilt Vergiftungen bei Mensch und Tier."),
    "creature_medicine": dict(name="Tiermedizin", cat="consumable", weight=0.2, stack=20, value=20, creature_heal=200, cure="injury", desc="Heilt Kreaturen und behandelt Verletzungen."),
    "purify_tonic": dict(name="Reinigungstrank", cat="consumable", weight=0.2, stack=10, value=40, cure="mutation", desc="Kann einen negativen Erbdefekt einer Kreatur lindern."),
    "gene_stabilizer": dict(name="Genstabilisator", cat="consumable", weight=0.1, stack=10, value=50, stabilize=0.2, desc="Senkt die Instabilität eines Hybriden."),
    "forget_potion": dict(name="Trank des Vergessens", cat="consumable", weight=0.2, stack=5, value=80, respec=True, desc="Setzt alle Fähigkeitenpunkte zurück."),
    "repel_musk": dict(name="Moschussalbe", cat="consumable", weight=0.1, stack=10, value=8, buff="moschus", desc="Kleine Räuber meiden dich 3 Minuten."),
    "research_notes": dict(name="Forschungsnotizen", cat="consumable", weight=0.05, stack=50, value=10, research=2, desc="Gibt 2 Forschungspunkte."),
    "ancient_tablet": dict(name="Uralte Steintafel", cat="consumable", weight=1.0, stack=10, value=30, research=5, desc="Inschriften der Vorfahren. Gibt 5 Forschungspunkte."),
    # ---------------------------------------------------------------- essences
    "demon_essence": dict(name="Dämonenessenz", cat="essence", weight=0.1, stack=50, value=20, desc="Pulsierende Rissmaterie. Basis für Pakte und Monster-Gene."),
    "elemental_essence": dict(name="Elementaressenz", cat="essence", weight=0.1, stack=50, value=18, desc="Ungebundene Elementarkraft."),
    "rift_shard": dict(name="Risssplitter", cat="essence", weight=0.3, stack=20, value=25, desc="Ein Splitter aus dem Riss. Flüstert."),
    "shadow_shard": dict(name="Schattensplitter", cat="essence", weight=0.2, stack=20, value=30),
    "blood_crystal": dict(name="Blutkristall", cat="essence", weight=0.3, stack=20, value=40),
    "demon_heart": dict(name="Dämonenherz", cat="essence", weight=1.0, stack=5, value=120, desc="Schlägt noch. Uralte Rituale verlangen danach."),
    "essence_hellhound": dict(name="Höllenhund-Essenz", cat="essence", weight=0.1, stack=20, value=40, monster="hellhound"),
    "essence_shadowstalker": dict(name="Pirscher-Essenz", cat="essence", weight=0.1, stack=20, value=55, monster="shadowstalker"),
    "essence_bonewyrm": dict(name="Wyrm-Essenz", cat="essence", weight=0.1, stack=20, value=80, monster="bonewyrm"),
    "essence_riftspider": dict(name="Weberinnen-Essenz", cat="essence", weight=0.1, stack=20, value=60, monster="riftspider"),
    # ---------------------------------------------------------------- weapons (base templates; crafted variants carry data)
    "spear_stone": dict(name="Steinspeer", cat="weapon", wtype="spear", weight=2.5, stack=1, value=8,
                        stats=dict(dmg=16, kind="pierce", speed=1.0, stam=10, reach=2.6, torpor=0), desc="Reichweite und Stoßangriffe."),
    "club_wood": dict(name="Holzkeule", cat="weapon", wtype="club", weight=3.0, stack=1, value=5,
                      stats=dict(dmg=10, kind="blunt", speed=0.9, stam=12, reach=2.0, torpor=18), desc="Betäubt Ziele (Bewusstlosigkeit)."),
    "axe_stone": dict(name="Steinaxt", cat="weapon", wtype="axe", weight=2.5, stack=1, value=8,
                      stats=dict(dmg=14, kind="cut", speed=0.95, stam=12, reach=2.0, torpor=0, harvest_wood=2.0, harvest_stone=0.6)),
    "pick_stone": dict(name="Steinspitzhacke", cat="weapon", wtype="pick", weight=3.0, stack=1, value=8,
                       stats=dict(dmg=11, kind="pierce", speed=0.85, stam=13, reach=2.0, torpor=0, harvest_wood=0.5, harvest_stone=2.2, harvest_ore=1.5)),
    "sword_metal": dict(name="Metallschwert", cat="weapon", wtype="sword", weight=3.0, stack=1, value=40,
                        stats=dict(dmg=30, kind="cut", speed=1.15, stam=11, reach=2.3, torpor=0), desc="Schnelle Kombos."),
    "bow_wood": dict(name="Jagdbogen", cat="weapon", wtype="bow", weight=1.5, stack=1, value=12,
                     stats=dict(dmg=18, kind="pierce", speed=1.0, stam=6, reach=60, ammo=["arrow_stone", "arrow_tranq", "arrow_metal", "arrow_fire"])),
    "bow_composite": dict(name="Kompositbogen", cat="weapon", wtype="bow", weight=1.8, stack=1, value=45,
                          stats=dict(dmg=30, kind="pierce", speed=1.1, stam=6, reach=80, ammo=["arrow_stone", "arrow_tranq", "arrow_metal", "arrow_fire"])),
    "crossbow": dict(name="Armbrust", cat="weapon", wtype="crossbow", weight=4.0, stack=1, value=60,
                     stats=dict(dmg=48, kind="pierce", speed=0.5, stam=4, reach=90, ammo=["bolt_metal", "bolt_tranq"])),
    "blowpipe": dict(name="Blasrohr", cat="weapon", wtype="blowpipe", weight=0.6, stack=1, value=15,
                     stats=dict(dmg=4, kind="pierce", speed=1.3, stam=3, reach=35, ammo=["dart_tranq"]), desc="Leise und präzise für Betäubungspfeile."),
    "staff_wood": dict(name="Wanderstab", cat="weapon", wtype="staff", weight=2.0, stack=1, value=6,
                       stats=dict(dmg=9, kind="blunt", speed=1.0, stam=8, reach=2.2, torpor=8, spell_power=1.0), desc="Fokus für Unterstützungsmagie."),
    "staff_crystal": dict(name="Kristallstab", cat="weapon", wtype="staff", weight=2.2, stack=1, value=60,
                          stats=dict(dmg=12, kind="blunt", speed=1.0, stam=8, reach=2.2, torpor=8, spell_power=1.6, bolt=24), desc="Verstärkt Magie, verschießt Elementarblitze."),
    "donnerrohr": dict(name="Donnerrohr", cat="weapon", wtype="gun", weight=5.0, stack=1, value=120,
                       stats=dict(dmg=85, kind="pierce", speed=0.3, stam=2, reach=70, ammo=["shot_iron"]), desc="Primitive Schusswaffe. Laut – lockt Raubtiere an."),
    "runenbuechse": dict(name="Runenbüchse", cat="weapon", wtype="gun", weight=4.0, stack=1, value=300,
                         stats=dict(dmg=70, kind="pierce", speed=0.6, stam=2, reach=90, ammo=["rune_charge"], spell_power=1.4), desc="Magisch-technische Waffe, verschießt Elementarladungen."),
    "shield_wood": dict(name="Holzschild", cat="weapon", wtype="shield", slot="offhand", weight=3.0, stack=1, value=8, stats=dict(block=0.6, parry=0.25)),
    "shield_metal": dict(name="Metallschild", cat="weapon", wtype="shield", slot="offhand", weight=5.0, stack=1, value=50, stats=dict(block=0.85, parry=0.3)),
    "torch": dict(name="Fackel", cat="tool", wtype="torch", weight=0.5, stack=5, value=2, stats=dict(dmg=6, kind="blunt", speed=1.0, stam=8, reach=1.8, element="fire"), desc="Licht. Hält manche Tiere auf Abstand."),
    "bola": dict(name="Bola", cat="ammo", wtype="throw", weight=0.4, stack=20, value=4, stats=dict(dmg=2, entangle=6.0, reach=30), desc="Fesselt kleine und mittlere Kreaturen kurzzeitig."),
    "javelin": dict(name="Wurfspeer", cat="ammo", wtype="throw", weight=1.2, stack=10, value=6, stats=dict(dmg=28, kind="pierce", reach=40)),
    "firebomb": dict(name="Feuertopf", cat="ammo", wtype="throw", weight=0.8, stack=10, value=12, stats=dict(dmg=30, kind="fire", reach=30, aoe=4.0, element="fire")),
    # ammo
    "arrow_stone": dict(name="Steinpfeil", cat="ammo", weight=0.05, stack=100, value=1, stats=dict(dmg_mult=1.0)),
    "arrow_metal": dict(name="Metallpfeil", cat="ammo", weight=0.06, stack=100, value=3, stats=dict(dmg_mult=1.5)),
    "arrow_tranq": dict(name="Betäubungspfeil", cat="ammo", weight=0.05, stack=100, value=4, stats=dict(dmg_mult=0.4, torpor=45)),
    "arrow_fire": dict(name="Brandpfeil", cat="ammo", weight=0.06, stack=100, value=4, stats=dict(dmg_mult=1.0, element="fire")),
    "bolt_metal": dict(name="Metallbolzen", cat="ammo", weight=0.08, stack=100, value=4, stats=dict(dmg_mult=1.0)),
    "bolt_tranq": dict(name="Betäubungsbolzen", cat="ammo", weight=0.08, stack=100, value=6, stats=dict(dmg_mult=0.35, torpor=110)),
    "dart_tranq": dict(name="Betäubungspfeilchen", cat="ammo", weight=0.02, stack=100, value=3, stats=dict(dmg_mult=1.0, torpor=60)),
    "shot_iron": dict(name="Eisenkugel", cat="ammo", weight=0.1, stack=50, value=5, stats=dict(dmg_mult=1.0)),
    "rune_charge": dict(name="Runenladung", cat="ammo", weight=0.05, stack=50, value=8, stats=dict(dmg_mult=1.0)),
    # ---------------------------------------------------------------- armor
    "armor_hide_head": dict(name="Lederkappe", cat="armor", slot="head", weight=1.0, stack=1, value=6, stats=dict(armor=3, cold=2), color=[0.35, 0.25, 0.17]),
    "armor_hide_chest": dict(name="Lederweste", cat="armor", slot="chest", weight=3.0, stack=1, value=10, stats=dict(armor=6, cold=4), color=[0.38, 0.27, 0.18]),
    "armor_hide_legs": dict(name="Lederhose", cat="armor", slot="legs", weight=2.0, stack=1, value=8, stats=dict(armor=4, cold=3), color=[0.3, 0.22, 0.15]),
    "armor_fur_chest": dict(name="Pelzmantel", cat="armor", slot="chest", weight=4.0, stack=1, value=20, stats=dict(armor=6, cold=14, heat=-6), color=[0.42, 0.34, 0.26]),
    "armor_bone_chest": dict(name="Knochenpanzer", cat="armor", slot="chest", weight=6.0, stack=1, value=25, stats=dict(armor=12, cold=2), color=[0.7, 0.66, 0.56]),
    "armor_bone_head": dict(name="Knochenhelm", cat="armor", slot="head", weight=2.0, stack=1, value=15, stats=dict(armor=6), color=[0.72, 0.68, 0.58]),
    "armor_chitin_chest": dict(name="Chitinpanzer", cat="armor", slot="chest", weight=5.0, stack=1, value=45, stats=dict(armor=18, poison=0.3), color=[0.15, 0.12, 0.1]),
    "armor_chitin_legs": dict(name="Chitinbeinlinge", cat="armor", slot="legs", weight=3.5, stack=1, value=35, stats=dict(armor=12), color=[0.15, 0.12, 0.1]),
    "armor_metal_chest": dict(name="Metallharnisch", cat="armor", slot="chest", weight=10.0, stack=1, value=90, stats=dict(armor=26), color=[0.45, 0.45, 0.47]),
    "armor_metal_head": dict(name="Metallhelm", cat="armor", slot="head", weight=4.0, stack=1, value=60, stats=dict(armor=12), color=[0.45, 0.45, 0.47]),
    "armor_wyvern_chest": dict(name="Wyvernschuppenrüstung", cat="armor", slot="chest", weight=6.0, stack=1, value=250, stats=dict(armor=32, fire=0.5), color=[0.5, 0.15, 0.1]),
    "trinket_beast": dict(name="Bestienzahn-Amulett", cat="armor", slot="trinket", weight=0.1, stack=1, value=40, stats=dict(bond_gain=0.25), desc="Gefährten fassen schneller Vertrauen."),
    "trinket_rift": dict(name="Rissamulett", cat="armor", slot="trinket", weight=0.1, stack=1, value=90, stats=dict(corruption_resist=0.5), desc="Schützt vor Verderbnis."),
    # ---------------------------------------------------------------- tools / taming / special
    "binding_rune": dict(name="Bindungsrune", cat="tool", weight=0.2, stack=10, value=60, desc="Bindet geschwächte magische Kreaturen (unter 30% LP)."),
    "pact_sigil": dict(name="Paktsiegel", cat="tool", weight=0.2, stack=10, value=80, desc="Ermöglicht einen Pakt mit einem Monster am Rissaltar."),
    "soul_crystal": dict(name="Seelenkristall", cat="special", weight=0.5, stack=1, value=200, desc="Tragbarer magischer Speicher für gebundene Kreaturen."),
    "saddle_small": dict(name="Leichter Sattel", cat="saddle", weight=4.0, stack=1, value=15, size=["medium"], desc="Für mittelgroße Reittiere."),
    "saddle_large": dict(name="Schwerer Sattel", cat="saddle", weight=10.0, stack=1, value=40, size=["large"], desc="Für große Reittiere."),
    "saddle_huge": dict(name="Kolosssattel", cat="saddle", weight=18.0, stack=1, value=90, size=["huge"], desc="Für riesige Reittiere."),
    "saddle_flyer": dict(name="Flugsattel", cat="saddle", weight=5.0, stack=1, value=50, mount="fly", desc="Für Flugkreaturen."),
    "saddle_sea": dict(name="Seesattel", cat="saddle", weight=6.0, stack=1, value=45, mount="swim", desc="Für Wasserkreaturen; mit Luftblase."),
    "egg": dict(name="Ei", cat="special", weight=2.0, stack=1, value=30, desc="Muss in einer Brutstätte ausgebrütet werden."),
    "trap_bear": dict(name="Fußfalle", cat="trap", weight=4.0, stack=5, value=12, stats=dict(dmg=30, hold=8.0), desc="Hält kleine bis mittlere Kreaturen fest."),
    "trap_net": dict(name="Netzfalle", cat="trap", weight=3.0, stack=5, value=15, stats=dict(dmg=0, hold=12.0, torpor=30), desc="Fängt unverletzt – ideal zum Zähmen."),
    "trap_spike": dict(name="Stachelgrube", cat="trap", weight=5.0, stack=5, value=10, stats=dict(dmg=60, hold=2.0), desc="Verletzt schwer, auch große Tiere."),
    "map_fragment": dict(name="Kartenfragment", cat="quest", weight=0.05, stack=10, value=0),
    "journal_page_1": dict(name="Tagebuchseite (Ewald I)", cat="quest", weight=0.05, stack=1, value=0, read=True),
    "journal_page_2": dict(name="Tagebuchseite (Ewald II)", cat="quest", weight=0.05, stack=1, value=0, read=True),
    "journal_page_3": dict(name="Tagebuchseite (Ewald III)", cat="quest", weight=0.05, stack=1, value=0, read=True),
    "ward_key": dict(name="Bannschlüssel", cat="quest", weight=0.3, stack=1, value=0, desc="Öffnet das Siegel des Narbenschlunds."),
    "grukk_totem": dict(name="Moosfell-Totem", cat="quest", weight=0.5, stack=1, value=0),
}

# elemental runes & essences
for e in ELEMENTS_LIST:
    ITEMS[f"rune_{e}"] = dict(name=f"{EL_DE[e]}rune", cat="rune", weight=0.1, stack=20, value=35, element=e,
                              desc=f"Verleiht Waffen das Element {EL_DE[e]}.")
    ITEMS[f"essence_{e}"] = dict(name=f"{EL_DE[e]}essenz", cat="essence", weight=0.1, stack=50, value=25, element=e,
                                 desc=f"Konzentrierte {EL_DE[e]}kraft. Für Runen und elementare Gene.")
