# Parts (hybrid traits), skills (12 trees), research tree.

# sockets: priority list of sockets to attach to. families_ok: families that can carry the part.
# effects: stat multipliers; abilities granted; traits.
ALL = ["theropod", "ornithopod", "quadruped", "mammal", "crocodilian", "wyvern", "pterosaur", "avian", "marine", "fish", "serpent", "arthropod"]
LAND = ["theropod", "ornithopod", "quadruped", "mammal", "crocodilian", "wyvern"]

PARTS = {
    "horns_brow": dict(name="Stirnhörner", sockets=["head_top"], size=0.5, families=LAND + ["serpent"], effects=dict(atk=1.08), abilities=["gore"], instability=0.04),
    "horn_nose": dict(name="Nasenhorn", sockets=["nose"], size=0.45, families=LAND, effects=dict(atk=1.04), abilities=["gore"], instability=0.02),
    "horns_short": dict(name="Kurzhörner", sockets=["head_top"], size=0.7, families=LAND + ["serpent", "arthropod"], effects=dict(atk=1.05), abilities=["charge"], instability=0.03),
    "horns_demon": dict(name="Dämonenhörner", sockets=["head_top"], size=0.55, families=ALL, effects=dict(atk=1.12), traits=["demonic"], instability=0.1, monster=True),
    "horns_ram": dict(name="Widderhörner", sockets=["head_top"], size=0.5, families=ALL, effects=dict(deff=1.06), abilities=["headbutt"], instability=0.05, monster=True),
    "frill": dict(name="Nackenschild", sockets=["frill", "neck_back"], size=0.85, families=["quadruped", "mammal", "theropod", "ornithopod", "crocodilian"], effects=dict(deff=1.12), abilities=["frill_display"], instability=0.06),
    "crest_dilo": dict(name="Doppelkamm", sockets=["head_top"], size=0.55, families=LAND + ["pterosaur"], effects=dict(), abilities=["poison_spit"], instability=0.03),
    "frill_neck": dict(name="Halskragen", sockets=["neck_back"], size=0.9, families=["theropod", "ornithopod", "wyvern", "serpent"], effects=dict(), abilities=["frill_display"], instability=0.02),
    "crest_parasaur": dict(name="Röhrenkamm", sockets=["head_top"], size=0.75, families=LAND, effects=dict(stam=1.08), abilities=["warning_call"], instability=0.03),
    "crest_ptera": dict(name="Flugkamm", sockets=["head_top"], size=0.6, families=ALL, effects=dict(spd=1.03), instability=0.02),
    "dome": dict(name="Kuppelschädel", sockets=["head_top"], size=0.6, families=LAND, effects=dict(deff=1.05), abilities=["headbutt"], instability=0.03),
    "plates": dict(name="Rückenplatten", sockets=["back_front", "back", "tail_mid"], size=0.75, multi=True, families=LAND + ["serpent"], effects=dict(deff=1.15, spd=0.97), abilities=["plate_guard"], instability=0.06),
    "spikes_back": dict(name="Rückenstacheln", sockets=["back"], size=0.6, families=ALL, effects=dict(deff=1.06, atk=1.03), traits=["thorns"], instability=0.04),
    "thagomizer": dict(name="Schwanzstacheln", sockets=["tail_tip"], size=1.6, families=LAND + ["marine", "serpent"], effects=dict(atk=1.05), abilities=["thagomizer_strike"], instability=0.05),
    "club": dict(name="Schwanzkeule", sockets=["tail_tip"], size=1.3, families=LAND + ["marine", "serpent"], effects=dict(atk=1.04, spd=0.98), abilities=["club_smash"], instability=0.05),
    "armor": dict(name="Knochenpanzer", sockets=["back"], size=1.0, families=["quadruped", "mammal", "crocodilian", "theropod"], effects=dict(deff=1.35, spd=0.85), abilities=["shell_up"], instability=0.1),
    "sail": dict(name="Sonnensegel", sockets=["back"], size=0.62, families=LAND + ["marine", "fish"], effects=dict(stam=1.1), traits=["sun_sail"], instability=0.05),
    "tusks": dict(name="Stoßzähne", sockets=["maw"], size=0.9, families=["quadruped", "mammal"], effects=dict(atk=1.1), abilities=["gore"], instability=0.05),
    "fangs": dict(name="Säbelzähne", sockets=["maw"], size=0.4, families=["mammal", "theropod", "quadruped", "crocodilian", "serpent"], effects=dict(atk=1.1), abilities=["saber_strike"], instability=0.05),
    "wing_membrane": dict(name="Hautflügel", sockets=["shoulder_L", "shoulder_R"], size=1.2, pair=True, families=["theropod", "ornithopod", "mammal", "quadruped", "wyvern"], effects=dict(spd=1.05, stam=0.95), traits=["glider"], abilities=["wing_buffet"], instability=0.18, research="chimera"),
    "wing_feather": dict(name="Federschwingen", sockets=["shoulder_L", "shoulder_R"], size=1.1, pair=True, families=["theropod", "ornithopod", "mammal"], effects=dict(spd=1.06), traits=["glider"], abilities=["wing_buffet"], instability=0.16, research="chimera"),
    "bone_spikes": dict(name="Knochenauswüchse", sockets=["back", "back_front", "tail_mid"], size=0.6, multi=True, families=ALL, effects=dict(atk=1.08, deff=1.05), traits=["demonic", "thorns"], instability=0.12, monster=True),
    "tail_demon": dict(name="Dämonenschweif", sockets=["tail_tip"], size=0.8, families=["humanoid"], effects=dict(), instability=0.0),
}

# --------------------------------------------------------------------------- skills
def S(tree, name, desc, max_rank=3, kind="passive", ability=None, req=None, lvl=1, per_rank=None):
    return dict(tree=tree, name=name, desc=desc, max=max_rank, kind=kind, ability=ability, req=req, level=lvl, per_rank=per_rank or {})


SKILL_TREES = {
    "melee": "Nahkampf", "ranged": "Fernkampf", "defense": "Verteidigung", "hunt": "Jagd & Fallen",
    "beast": "Bestienführung", "taming": "Zähmung & Bindung", "genetics": "Genetik & Hybridisierung",
    "craft": "Handwerk & Forschung", "elemental": "Elementarmagie", "healing": "Heilung & Schutz",
    "survival": "Überleben & Alchemie", "explore": "Erkundung & Bewegung",
}

SKILLS = {
    "melee_power": S("melee", "Wucht", "+8% Nahkampfschaden pro Rang.", per_rank=dict(melee_dmg=0.08)),
    "melee_combo": S("melee", "Kombokette", "Schnellere Kombos; Rang 2: vierter Kombo-Schlag.", 2, per_rank=dict(combo_speed=0.1)),
    "power_strike": S("melee", "Kraftschlag", "Aktive Fähigkeit: wuchtiger, betäubender Schlag.", 1, "active", "power_strike", req="melee_power", lvl=3),
    "whirlwind": S("melee", "Wirbel", "Aktive Fähigkeit: Rundumschlag.", 1, "active", "whirlwind", req="melee_combo", lvl=8),
    "melee_execute": S("melee", "Henker", "+25% Schaden gegen Ziele unter 30% LP pro Rang.", 2, per_rank=dict(execute=0.25), lvl=12),
    "ranged_aim": S("ranged", "Ruhige Hand", "+8% Fernkampfschaden, weniger Streuung.", per_rank=dict(ranged_dmg=0.08)),
    "ranged_draw": S("ranged", "Schnellspannen", "Bogen/Armbrust 12% schneller.", 3, per_rank=dict(draw_speed=0.12)),
    "aimed_shot": S("ranged", "Gezielter Schuss", "Aktiv: verdoppelter Schaden, Durchschlag.", 1, "active", "aimed_shot", req="ranged_aim", lvl=3),
    "multishot": S("ranged", "Salve", "Aktiv: drei Pfeile im Fächer.", 1, "active", "multishot", req="ranged_draw", lvl=8),
    "ranged_tranq": S("ranged", "Betäubungsschütze", "+20% Betäubungswirkung pro Rang.", 3, per_rank=dict(torpor=0.2)),
    "def_block": S("defense", "Schildwall", "Blocken kostet 15% weniger Ausdauer und blockt mehr.", per_rank=dict(block=0.15)),
    "def_parry": S("defense", "Parade", "Größeres Paradefenster; Konter-Schaden +20%.", 2, per_rank=dict(parry=0.05)),
    "def_armor": S("defense", "Abhärtung", "+6% Rüstung pro Rang.", per_rank=dict(armor=0.06)),
    "def_vitality": S("defense", "Lebenskraft", "+15 maximale LP pro Rang.", 5, per_rank=dict(hp=15)),
    "def_second_wind": S("defense", "Zweiter Atem", "Einmal pro Kampf: bei <20% LP heilst du 30%.", 1, req="def_vitality", lvl=10),
    "hunt_tracking": S("hunt", "Fährtenlesen", "Zeigt Stufe, Zustand und Zähmbarkeit wilder Tiere; Rang 3: Alphas auf Karte.", per_rank=dict(tracking=1)),
    "hunt_skinning": S("hunt", "Ausweiden", "+20% Beute aus Kadavern.", per_rank=dict(loot=0.2)),
    "hunt_traps": S("hunt", "Fallensteller", "Fallen halten 25% länger; schaltet Fallenbau frei.", per_rank=dict(trap=0.25)),
    "hunt_stealth": S("hunt", "Lautlos", "Geduckt werden wilde Tiere später aufmerksam.", per_rank=dict(stealth=0.2)),
    "hunt_bola": S("hunt", "Wurfmeister", "Bolas & Wurfspeere +25% Wirkung.", 2, per_rank=dict(throw=0.25)),
    "beast_command": S("beast", "Rudelführer", "+1 Gefährte im aktiven Gefolge pro Rang.", 3, per_rank=dict(party=1)),
    "beast_pack": S("beast", "Großes Gefolge", "+1 Gefährte; Gefährten folgen enger in Formation.", 2, req="beast_command", lvl=10, per_rank=dict(party=1)),
    "beast_tactics": S("beast", "Taktik", "+8% Schaden deiner Gefährten pro Rang.", per_rank=dict(companion_dmg=0.08)),
    "beast_rally": S("beast", "Bestienruf", "Aktiv: Gefährten +25% Schaden/Tempo.", 1, "active", "beast_rally", req="beast_tactics", lvl=6),
    "beast_mount": S("beast", "Reiterkunst", "Reitkampf: +15% Schaden vom Sattel, Reittier +10% Tempo.", 2, per_rank=dict(mount=0.15)),
    "tame_trust": S("taming", "Sanfte Hand", "Vertrauenszähmung 25% schneller; Tiere fliehen später.", per_rank=dict(trust=0.25)),
    "tame_knockout": S("taming", "Bändiger", "Betäubungszähmung 20% schneller; Betäubung hält länger.", per_rank=dict(ko_tame=0.2)),
    "tame_bond": S("taming", "Seelenband", "+25% Bindungsgewinn.", per_rank=dict(bond=0.25)),
    "tame_magic": S("taming", "Runenbinder", "+12% Chance bei magischer Bindung und Pakten.", per_rank=dict(magic_bind=0.12), lvl=6),
    "tame_imprint": S("taming", "Prägung", "Geschlüpfte Tiere starten mit +15 Bindung und besseren Werten.", 2, per_rank=dict(imprint=0.15)),
    "gen_insight": S("genetics", "Geneinsicht", "Zeigt Genwerte; Rang 2: Vererbungschancen; Rang 3: verborgene Mutationen.", per_rank=dict(insight=1)),
    "gen_control": S("genetics", "Vererbungslenkung", "+15% Kontrolle über vererbte Merkmale.", per_rank=dict(control=0.15), req="gen_insight"),
    "gen_stability": S("genetics", "Stabile Linien", "-15% Instabilität bei Kreuzungen.", per_rank=dict(stability=0.15)),
    "gen_mutation": S("genetics", "Mutagenese", "+30% Chance auf positive Mutationen.", 2, per_rank=dict(mutation=0.3), lvl=8),
    "gen_chimera": S("genetics", "Chimärenkunde", "Familienübergreifende Kreuzungen weniger riskant.", 2, per_rank=dict(chimera=0.2), lvl=12, req="gen_control"),
    "craft_quality": S("craft", "Meisterhand", "+8% Qualität hergestellter Ausrüstung.", 5, per_rank=dict(quality=0.08)),
    "craft_efficiency": S("craft", "Sparsamkeit", "10% Chance pro Rang, keine Materialien zu verbrauchen.", per_rank=dict(save_mat=0.1)),
    "craft_research": S("craft", "Gelehrter", "+25% Forschungspunkte.", per_rank=dict(research=0.25)),
    "craft_runes": S("craft", "Runenschmied", "Runen verleihen +20% Elementarschaden.", 2, per_rank=dict(rune=0.2), lvl=8),
    "craft_salvage": S("craft", "Verwerter", "Zerlegen gibt mehr Material zurück.", 2, per_rank=dict(salvage=0.25)),
    "firebolt": S("elemental", "Feuerlanze", "Aktiv: Feuergeschoss.", 1, "active", "firebolt", lvl=5, req="elemental_affinity"),
    "ice_shard": S("elemental", "Eissplitter", "Aktiv: unterkühlendes Geschoss.", 1, "active", "ice_shard", lvl=5, req="elemental_affinity"),
    "lightning_arc": S("elemental", "Blitzbogen", "Aktiv: überspringender Blitz.", 1, "active", "lightning_arc", lvl=10, req="firebolt"),
    "elemental_affinity": S("elemental", "Elementargespür", "Erlernbar nach Nixas Unterricht. +10% Elementarschaden.", 3, per_rank=dict(element_dmg=0.1), lvl=4),
    "elemental_mastery": S("elemental", "Reaktionsmeister", "Elementarreaktionen +20% Wirkung.", 2, per_rank=dict(reaction=0.2), lvl=12, req="elemental_affinity"),
    "heal_mend": S("healing", "Heilkunde", "+20% Heilkraft pro Rang.", 5, per_rank=dict(heal=0.2)),
    "heal_wave": S("healing", "Heilende Welle", "Aktiv: Gruppenheilung.", 1, "active", "heal_wave", req="heal_mend", lvl=6),
    "ward": S("healing", "Schutzglyphe", "Aktiv: Schild für dich oder Gefährten.", 1, "active", "ward", lvl=4),
    "cleanse": S("healing", "Reinigen", "Aktiv: entfernt negative Zustände.", 1, "active", "cleanse", lvl=6),
    "beast_mend": S("healing", "Tierheilung", "Aktiv: starke Heilung eines Gefährten.", 1, "active", "beast_mend", lvl=3),
    "surv_hunger": S("survival", "Genügsam", "Hunger sinkt 15% langsamer.", per_rank=dict(hunger=0.15)),
    "surv_alchemy": S("survival", "Alchemist", "+20% Trankwirkung; Rang 2: 1 Extra-Ergebnis.", per_rank=dict(potion=0.2)),
    "surv_forage": S("survival", "Sammler", "+25% Ertrag beim Sammeln.", per_rank=dict(gather=0.25)),
    "surv_climate": S("survival", "Wetterfest", "+30% Kälte/Hitze-Resistenz.", 2, per_rank=dict(climate=0.3)),
    "surv_regen": S("survival", "Zähigkeit", "+50% LP-Regeneration außerhalb des Kampfes.", 2, per_rank=dict(regen=0.5)),
    "exp_sprint": S("explore", "Ausdauerläufer", "Sprinten kostet 15% weniger Ausdauer.", per_rank=dict(sprint=0.15)),
    "exp_swim": S("explore", "Taucher", "+50% Atem und +15% Schwimmtempo.", per_rank=dict(swim=0.5)),
    "exp_climb": S("explore", "Kletterer", "Rang 1: steilere Hänge begehbar. Rang 2: Klettern an Felswänden.", 2, per_rank=dict(climb=1)),
    "exp_cartography": S("explore", "Kartograf", "Zeigt Orte in der Nähe auf der Karte.", 2, per_rank=dict(carto=1)),
    "exp_dodge": S("explore", "Akrobat", "Ausweichen kostet weniger und gewährt längere Unverwundbarkeit.", per_rank=dict(dodge=0.15)),
}

DEMON_SKILLS = {
    "d_claws": dict(name="Klauenwirbel", desc="Aktiv: Klauen-Rundumschlag.", max=1, kind="active", ability="d_claws", level=1),
    "d_hellfire": dict(name="Höllenfeuer", desc="Aktiv: dämonisches Feuergeschoss.", max=1, kind="active", ability="d_hellfire", level=2),
    "d_shadowstep": dict(name="Schattensprung", desc="Aktiv: Teleport hinter das Ziel.", max=1, kind="active", ability="d_shadowstep", level=3),
    "d_bloodfrenzy": dict(name="Blutrausch", desc="Aktiv: Schaden & Lebensraub.", max=1, kind="active", ability="d_bloodfrenzy", level=4),
    "d_terror": dict(name="Schreckensbrüllen", desc="Aktiv: Furcht im Umkreis.", max=1, kind="active", ability="d_terror", level=5),
    "d_hide": dict(name="Höllenhaut", desc="+10% Rüstung in Dämonengestalt pro Rang.", max=3, kind="passive", level=1, per_rank=dict(d_armor=0.1)),
    "d_might": dict(name="Urgewalt", desc="+10% Schaden in Dämonengestalt pro Rang.", max=3, kind="passive", level=1, per_rank=dict(d_dmg=0.1)),
    "d_wings": dict(name="Schwingen der Tiefe", desc="Dämonenflügel erlauben Gleitflug; Rang 2: echter Flug.", max=2, kind="passive", level=3),
    "d_elements": dict(name="Elementarkern", desc="Gewählte Elementar-Rune färbt deine Dämonenkräfte.", max=1, kind="passive", level=6),
}

# --------------------------------------------------------------------------- research
def R(name, cost, desc, req=None, source="start", items=None, unlocks=None, cat="Handwerk"):
    return dict(name=name, cost=cost, desc=desc, req=req or [], source=source, items=items or {}, unlocks=unlocks or [], cat=cat)


RESEARCH = {
    "carpentry": R("Zimmerei", 3, "Betten, große Lager, stabile Bauten.", unlocks=["bed", "storage_large"]),
    "masonry": R("Steinbau", 5, "Steinmauern und Mörtel.", req=["carpentry"], unlocks=["stone_wall"]),
    "fortification": R("Befestigung", 6, "Wachtürme.", req=["masonry"], unlocks=["watchtower"]),
    "agriculture": R("Ackerbau", 4, "Feldbeete für Bewohner.", unlocks=["farm_plot"], cat="Siedlung"),
    "cooking": R("Kochkunst", 3, "Kochstelle, Trockenfleisch, Eintopf.", unlocks=["kitchen"], cat="Überleben"),
    "alchemy_basics": R("Alchemie", 3, "Alchemietisch, Salben, Tonika.", unlocks=["alchemy_table"], cat="Überleben"),
    "potency": R("Wirkstofflehre", 6, "Heiltränke, Trank des Vergessens.", req=["alchemy_basics"], cat="Überleben"),
    "veterinary": R("Tierheilkunde", 5, "Krankenstation, Tiermedizin.", req=["alchemy_basics"], source="teacher:ilsa", cat="Bestien"),
    "beast_lore": R("Bestienkunde", 4, "Bestienfutter und Zahnamulett.", source="start", cat="Bestien"),
    "tranquilizers": R("Betäubungskunde", 3, "Blasrohr und Betäubungspfeilchen.", cat="Bestien"),
    "trapping": R("Fallenbau", 4, "Fuß-, Netz- und Stachelfallen.", cat="Jagd"),
    "saddlery": R("Sattlerei", 4, "Leichte und schwere Sättel.", cat="Bestien"),
    "saddlery_2": R("Kolosssattel", 8, "Sättel für riesige Kreaturen.", req=["saddlery", "metallurgy"], cat="Bestien"),
    "flight_harness": R("Fluggeschirr", 7, "Flugsattel und Flugplattform.", req=["saddlery"], source="investigate:pteranodon", cat="Bestien"),
    "sea_harness": R("Seegeschirr", 7, "Seesattel und Wassergehege.", req=["saddlery"], source="investigate:plesiosaurus", cat="Bestien"),
    "husbandry_2": R("Großtierhaltung", 6, "Großgehege.", req=["carpentry"], cat="Siedlung"),
    "crystal_2": R("Kristallresonanz", 8, "Seelenkristall +2 Kapazität; Kristalle herstellbar.", source="quest:q5_spuren", cat="Magie"),
    "crystal_3": R("Kristallharmonie", 14, "Seelenkristall +3 Kapazität.", req=["crystal_2"], cat="Magie"),
    "metallurgy": R("Metallurgie", 6, "Schmiede, Metallwaffen und -rüstungen.", source="teacher:tomas", cat="Handwerk"),
    "mechanics": R("Mechanik", 8, "Armbrust und Bolzen.", req=["metallurgy"], cat="Handwerk"),
    "black_powder": R("Schwarzpulver", 12, "Donnerrohr: primitive Feuerwaffe.", req=["mechanics"], source="teacher:brannoc", cat="Handwerk"),
    "runetech": R("Runentechnik", 18, "Runenbüchse: magisch-technische Waffe.", req=["black_powder", "runecraft"], cat="Magie"),
    "incendiaries": R("Brandmittel", 5, "Feuertöpfe und Brandpfeile.", req=["alchemy_basics"], cat="Jagd"),
    "bone_craft": R("Knochenschnitzerei", 3, "Knochenrüstung.", cat="Handwerk"),
    "chitin_craft": R("Chitinverarbeitung", 6, "Chitinrüstung.", source="investigate:spider", cat="Handwerk"),
    "cold_gear": R("Winterausrüstung", 3, "Pelzmantel.", cat="Überleben"),
    "advanced_archery": R("Bogenbaukunst", 6, "Kompositbogen.", cat="Jagd"),
    "dragon_smith": R("Drachenschmiede", 16, "Wyvernschuppenrüstung.", req=["metallurgy"], source="investigate:wyvern", cat="Handwerk"),
    "element_theory": R("Elementlehre", 5, "Essenzen destillieren; Elementplätze für Kreaturen.", source="teacher:nixa", cat="Magie"),
    "runecraft": R("Runenkunde", 6, "Elementarrunen (Feuer bis Gift).", req=["element_theory"], cat="Magie"),
    "runecraft_2": R("Hohe Runen", 10, "Licht-, Schatten- und Blutrunen.", req=["runecraft"], cat="Magie"),
    "element_fusion_1": R("Elementfusion I", 8, "Elementplätze mit Zweiermischungen.", req=["element_theory"], cat="Magie"),
    "element_fusion_2": R("Elementfusion II", 14, "Dreiermischungen.", req=["element_fusion_1"], cat="Magie"),
    "element_fusion_3": R("Elementfusion III", 22, "Vier- und Fünfermischungen (hohe Instabilität).", req=["element_fusion_2"], cat="Magie"),
    "crystal_focus": R("Kristallfokus", 8, "Kristallstab.", req=["element_theory"], cat="Magie"),
    "binding_magic": R("Bindungsmagie", 6, "Bindungsrunen für magische Kreaturen.", source="teacher:nixa", cat="Magie"),
    "rift_analysis": R("Rissanalyse", 6, "Verstehe die Risse. Rissamulett.", source="quest:q5_spuren", items={"rift_shard": 3}, cat="Magie"),
    "pact_lore": R("Paktkunde", 12, "Rissaltar, Paktsiegel – Monster durch Pakte gewinnen.", req=["rift_analysis"], source="ruin:schrein", cat="Magie"),
    "genetics_1": R("Genetik", 6, "Genlabor: Kreuzungen innerhalb einer Körperfamilie.", source="quest:q6_blut", cat="Genetik"),
    "genetics_2": R("Vererbungslehre", 10, "Manueller Hybrid-Editor, gespeicherte Rezepte.", req=["genetics_1"], cat="Genetik"),
    "chimera": R("Chimärenforschung", 16, "Familienübergreifende Kreuzungen, Flügel als Hybridteil.", req=["genetics_2"], cat="Genetik"),
    "monster_genes": R("Monstergenetik", 18, "Monsteressenzen in Hybriden – sichtbare Monster-Dino-Hybriden.", req=["chimera", "rift_analysis"], cat="Genetik"),
    "gene_therapy": R("Gentherapie", 10, "Reinigungstrank und Genstabilisator.", req=["genetics_1", "alchemy_basics"], cat="Genetik"),
    "cartography": R("Kartografie", 4, "Zeigt alle Orte einer Insel auf der Karte nach Betreten.", cat="Erkundung"),
}
