# Species definitions (source of truth -> data/species.json)
# stats: hp, atk, def(0..1 dmg reduction-ish points), spd (run m/s), stam, carry (kg)
# size: small (0.5 storage), medium (1), large (2), huge (4)

def C(*rgb):
    return list(rgb)


SPECIES = {
    "trex": dict(
        name="Tyrannosaurus", rig="trex", family="theropod", size="huge", diet="carnivore",
        food=["raw_prime_meat", "raw_meat"], biomes=["grassland", "forest", "jungle"],
        social="solitary", temper="predator", aggro=38, levels=[12, 40],
        stats=dict(hp=1800, atk=90, deff=30, spd=9.5, walk=3.5, stam=420, carry=500),
        abilities=["heavy_bite", "roar", "tail_swipe", "stomp"], passives=["apex", "bone_crusher"],
        tame=dict(method="knockout", difficulty=3.0, torpor=1200), rideable=True, mount="ground",
        rider_weapons=["bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.33, 0.29, 0.22), belly=C(0.62, 0.55, 0.42), pattern=C(0.17, 0.14, 0.11), pt=1),
                dict(main=C(0.28, 0.27, 0.24), belly=C(0.55, 0.52, 0.45), pattern=C(0.4, 0.15, 0.1), pt=3)],
        parts=[], xp=420, loot=[["raw_prime_meat", 6, 10], ["hide", 8, 14], ["large_bone", 3, 6], ["trex_tooth", 1, 3]],
        lore="Der unangefochtene Herrscher der Ebenen. Sein Biss zermalmt Knochen und Panzer gleichermaßen. "
             "Junge Tiere jagen im Wald, alte Einzelgänger beanspruchen ganze Täler.",
        sounds="roar_big"),
    "atrociraptor": dict(
        name="Atrociraptor", rig="atrociraptor", family="theropod", size="small", diet="carnivore",
        food=["raw_meat"], biomes=["forest", "jungle"], social="pack", temper="predator", aggro=26, levels=[1, 25],
        stats=dict(hp=170, atk=22, deff=6, spd=12.5, walk=3.0, stam=200, carry=60),
        abilities=["bite", "pounce", "pack_call"], passives=["pack_hunter"],
        tame=dict(method="knockout", difficulty=1.0, torpor=200), rideable=False, mount="",
        colors=[dict(main=C(0.42, 0.2, 0.12), belly=C(0.7, 0.55, 0.4), pattern=C(0.12, 0.08, 0.06), pt=1),
                dict(main=C(0.25, 0.22, 0.2), belly=C(0.6, 0.55, 0.5), pattern=C(0.55, 0.15, 0.1), pt=2)],
        parts=[], xp=45, loot=[["raw_meat", 1, 3], ["hide", 1, 3], ["raptor_claw", 0, 1]],
        lore="Kurzschnäuziger Rudeljäger mit tiefem Kiefer. Atrociraptoren hetzen Beute in Dreiergruppen "
             "und greifen gezielt Flanken an.", sounds="screech"),
    "raptor": dict(
        name="Velociraptor", rig="raptor", family="theropod", size="small", diet="carnivore",
        food=["raw_meat", "raw_fish"], biomes=["forest", "grassland", "jungle"], social="pack", temper="predator",
        aggro=24, levels=[1, 30], stats=dict(hp=150, atk=18, deff=5, spd=13.0, walk=3.0, stam=220, carry=70),
        abilities=["bite", "pounce", "pack_call", "slash_claw"], passives=["pack_hunter", "sickle_claw"],
        tame=dict(method="egg", difficulty=1.0), rideable=True, mount="ground", min_ride_level=8,
        rider_weapons=["spear", "sword", "axe", "bow", "throw"],
        colors=[dict(main=C(0.45, 0.38, 0.26), belly=C(0.72, 0.65, 0.5), pattern=C(0.2, 0.15, 0.1), pt=1),
                dict(main=C(0.3, 0.33, 0.3), belly=C(0.65, 0.62, 0.55), pattern=C(0.12, 0.2, 0.25), pt=2)],
        parts=[], xp=40, loot=[["raw_meat", 1, 2], ["hide", 1, 2], ["raptor_claw", 0, 1]],
        lore="Klein, schnell und erschreckend klug. Velociraptoren lassen sich nur von Geburt an prägen – "
             "ihre Eier liegen in gut bewachten Nestern im Unterholz.", sounds="screech"),
    "spinosaurus": dict(
        name="Spinosaurus", rig="spinosaurus", family="theropod", size="huge", diet="piscivore",
        food=["raw_fish", "raw_prime_fish", "raw_meat"], biomes=["swamp", "coast"], social="solitary",
        temper="territorial", aggro=30, levels=[15, 45],
        stats=dict(hp=1500, atk=70, deff=22, spd=8.0, walk=3.0, stam=400, carry=450, swim=9.0),
        abilities=["heavy_bite", "claw_rake", "tail_swipe", "roar"], passives=["amphibious", "sun_sail"],
        tame=dict(method="knockout", difficulty=2.5, torpor=1000), rideable=True, mount="amphibious",
        rider_weapons=["bow", "crossbow", "throw", "staff", "spear"],
        colors=[dict(main=C(0.3, 0.3, 0.27), belly=C(0.6, 0.58, 0.5), pattern=C(0.45, 0.2, 0.12), pt=3)],
        parts=[dict(id="sail", socket="back", size=0.62)], xp=380,
        loot=[["raw_prime_meat", 4, 8], ["hide", 6, 10], ["large_bone", 2, 5], ["sail_membrane", 1, 2]],
        lore="Halb Fisch-, halb Landjäger. Das Rückensegel speichert Sonnenwärme – ein Spinosaurus im "
             "Sonnenlicht erholt sich schneller.", sounds="roar_big"),
    "carnotaurus": dict(
        name="Carnotaurus", rig="carnotaurus", family="theropod", size="large", diet="carnivore",
        food=["raw_meat", "raw_prime_meat"], biomes=["grassland", "desert"], social="solitary",
        temper="predator", aggro=32, levels=[8, 35],
        stats=dict(hp=800, atk=45, deff=14, spd=12.0, walk=3.2, stam=380, carry=260),
        abilities=["bite", "charge", "roar"], passives=["sprinter"],
        tame=dict(method="knockout", difficulty=1.8, torpor=600), rideable=True, mount="ground",
        rider_weapons=["spear", "sword", "axe", "bow", "crossbow", "throw"],
        colors=[dict(main=C(0.5, 0.25, 0.16), belly=C(0.7, 0.55, 0.42), pattern=C(0.2, 0.1, 0.07), pt=3)],
        parts=[dict(id="horns_short", socket="head_top", size=0.75)], xp=180,
        loot=[["raw_meat", 4, 7], ["hide", 4, 7], ["large_bone", 1, 3]],
        lore="Der gehörnte Sprinter. Bei vollem Lauf ist ein Carnotaurus kaum einzuholen, "
             "doch auf engem Raum wendet er schwerfällig.", sounds="roar_mid"),
    "dilophosaurus": dict(
        name="Dilophosaurus", rig="dilophosaurus", family="theropod", size="medium", diet="carnivore",
        food=["raw_meat", "raw_fish"], biomes=["jungle", "swamp"], social="pack", temper="territorial",
        aggro=18, levels=[1, 25], stats=dict(hp=200, atk=16, deff=6, spd=9.0, walk=2.8, stam=200, carry=90),
        abilities=["bite", "poison_spit", "frill_display"], passives=["venomous"],
        tame=dict(method="egg", difficulty=1.0), rideable=False, mount="",
        colors=[dict(main=C(0.32, 0.38, 0.22), belly=C(0.65, 0.62, 0.45), pattern=C(0.6, 0.45, 0.1), pt=2)],
        parts=[dict(id="crest_dilo", socket="head_top", size=0.55), dict(id="frill_neck", socket="neck_back", size=0.9)],
        elements={"poison": 0.6}, xp=50, loot=[["raw_meat", 1, 3], ["hide", 1, 3], ["venom_gland", 0, 1]],
        lore="Bei Gefahr spreizt er einen Halskragen und spuckt lähmendes Gift. "
             "Dorfbewohner reiben sich mit Moschuskraut ein, um nicht angegriffen zu werden.", sounds="hiss"),
    "gallimimus": dict(
        name="Gallimimus", rig="gallimimus", family="theropod", size="medium", diet="omnivore",
        food=["berries", "veggies", "raw_fish"], biomes=["grassland", "coast"], social="herd", temper="skittish",
        aggro=0, levels=[1, 30], stats=dict(hp=180, atk=8, deff=4, spd=15.5, walk=3.5, stam=420, carry=120),
        abilities=["kick", "sprint_burst"], passives=["sprinter", "herd_alarm"],
        tame=dict(method="trust", difficulty=1.0, feedings=3), rideable=True, mount="ground",
        rider_weapons=["spear", "sword", "axe", "bow", "throw", "staff"],
        colors=[dict(main=C(0.55, 0.47, 0.35), belly=C(0.82, 0.78, 0.68), pattern=C(0.35, 0.25, 0.18), pt=2)],
        parts=[], xp=30, loot=[["raw_meat", 1, 3], ["feather", 1, 3], ["hide", 0, 2]],
        lore="Der schnellste Läufer der Ebenen. Herden reagieren nervös auf jede schnelle Bewegung – "
             "wer sich geduckt nähert und Beeren bietet, gewinnt ihr Vertrauen.", sounds="chirp"),
    "compy": dict(
        name="Compsognathus", rig="compy", family="theropod", size="small", diet="carnivore",
        food=["raw_meat", "raw_fish"], biomes=["forest", "jungle", "coast"], social="pack", temper="skittish",
        aggro=8, levels=[1, 15], stats=dict(hp=30, atk=4, deff=1, spd=8.0, walk=2.0, stam=100, carry=10),
        abilities=["bite", "pack_call"], passives=["scavenger"],
        tame=dict(method="trust", difficulty=0.5, feedings=2), rideable=False, mount="",
        colors=[dict(main=C(0.35, 0.4, 0.25), belly=C(0.7, 0.68, 0.5), pattern=C(0.15, 0.2, 0.1), pt=1)],
        parts=[], xp=8, loot=[["raw_meat", 1, 1]],
        lore="Aasfresser, die Großräubern folgen. Allein harmlos, als Schwarm lästig.", sounds="chirp"),
    "parasaurolophus": dict(
        name="Parasaurolophus", rig="parasaurolophus", family="ornithopod", size="large", diet="herbivore",
        food=["veggies", "berries", "rare_flower"], biomes=["forest", "grassland", "swamp"], social="herd",
        temper="skittish", aggro=0, levels=[1, 30], stats=dict(hp=500, atk=12, deff=8, spd=10.5, walk=3.0, stam=380, carry=280),
        abilities=["kick", "warning_call", "harvest"], passives=["herd_alarm", "echo_sense"],
        tame=dict(method="trust", difficulty=1.2, feedings=4), rideable=True, mount="ground",
        rider_weapons=["spear", "sword", "axe", "bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.42, 0.38, 0.28), belly=C(0.72, 0.66, 0.52), pattern=C(0.6, 0.3, 0.12), pt=3)],
        parts=[dict(id="crest_parasaur", socket="head_top", size=0.75)], xp=60,
        loot=[["raw_meat", 2, 5], ["hide", 2, 5], ["fiber", 0, 3]],
        lore="Mit dem hohlen Kopfkamm warnen sie die Herde über weite Strecken. "
             "Ein vertrautes Tier ist das ideale erste Reittier.", sounds="horn_call"),
    "pachycephalosaurus": dict(
        name="Pachycephalosaurus", rig="pachycephalosaurus", family="ornithopod", size="medium", diet="herbivore",
        food=["veggies", "berries"], biomes=["grassland", "forest", "snow"], social="herd", temper="territorial",
        aggro=10, levels=[1, 30], stats=dict(hp=260, atk=20, deff=12, spd=9.5, walk=3.0, stam=260, carry=120),
        abilities=["charge", "headbutt"], passives=["hard_head"],
        tame=dict(method="trust", difficulty=1.3, feedings=3), rideable=True, mount="ground", min_ride_level=5,
        rider_weapons=["spear", "sword", "axe", "throw"],
        colors=[dict(main=C(0.4, 0.33, 0.28), belly=C(0.68, 0.6, 0.5), pattern=C(0.25, 0.18, 0.15), pt=4)],
        parts=[dict(id="dome", socket="head_top", size=0.6)], xp=40,
        loot=[["raw_meat", 1, 3], ["hide", 1, 3], ["bone", 1, 2]],
        lore="Rammt alles, was sein Revier betritt – auch Felsen. Sein Kuppelschädel ist ein natürlicher Rammbock.",
        sounds="grunt"),
    "triceratops": dict(
        name="Triceratops", rig="triceratops", family="quadruped", size="large", diet="herbivore",
        food=["veggies", "berries", "rare_flower"], biomes=["grassland", "forest"], social="herd",
        temper="territorial", aggro=14, levels=[3, 40], stats=dict(hp=1200, atk=38, deff=28, spd=7.5, walk=2.6, stam=420, carry=500),
        abilities=["gore", "charge", "harvest", "stomp"], passives=["armored_head", "herd_guardian"],
        tame=dict(method="knockout", difficulty=1.5, torpor=800), rideable=True, mount="ground",
        rider_weapons=["spear", "sword", "axe", "bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.36, 0.34, 0.27), belly=C(0.6, 0.57, 0.46), pattern=C(0.5, 0.25, 0.15), pt=3),
                dict(main=C(0.3, 0.33, 0.3), belly=C(0.58, 0.58, 0.5), pattern=C(0.15, 0.25, 0.3), pt=2)],
        parts=[dict(id="frill", socket="frill", size=0.85), dict(id="horns_brow", socket="head_top", size=0.48),
               dict(id="horn_nose", socket="nose", size=0.45)],
        xp=160, loot=[["raw_meat", 4, 8], ["hide", 5, 9], ["horn", 1, 3], ["large_bone", 1, 2]],
        lore="Herdenwächter mit Nackenschild. Bedrängte Triceratops bilden einen Kreis um ihre Jungen und "
             "greifen jeden Räuber frontal an.", sounds="bellow"),
    "stegosaurus": dict(
        name="Stegosaurus", rig="stegosaurus", family="quadruped", size="large", diet="herbivore",
        food=["veggies", "berries"], biomes=["forest", "grassland"], social="herd", temper="territorial",
        aggro=10, levels=[3, 40], stats=dict(hp=1100, atk=34, deff=32, spd=5.5, walk=2.2, stam=380, carry=550),
        abilities=["thagomizer_strike", "plate_guard", "harvest"], passives=["plated_back"],
        tame=dict(method="rescue", difficulty=1.0), rideable=True, mount="ground",
        rider_weapons=["spear", "sword", "axe", "bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.33, 0.36, 0.28), belly=C(0.6, 0.6, 0.48), pattern=C(0.55, 0.35, 0.15), pt=1)],
        parts=[dict(id="plates", socket="neck_back", size=0.7), dict(id="plates", socket="back_front", size=0.75),
               dict(id="plates", socket="back", size=0.75), dict(id="plates", socket="tail_mid", size=1.0),
               dict(id="thagomizer", socket="tail_tip", size=1.6)],
        xp=150, loot=[["raw_meat", 4, 8], ["hide", 4, 8], ["keratin_plate", 1, 3]],
        lore="Bleibt gerne in Teergruben und Sumpflöchern stecken. Wer einem gefangenen Stegosaurus hilft, "
             "gewinnt einen treuen Freund.", sounds="bellow"),
    "ankylosaurus": dict(
        name="Ankylosaurus", rig="ankylosaurus", family="quadruped", size="large", diet="herbivore",
        food=["veggies", "berries"], biomes=["grassland", "mountain", "desert"], social="solitary",
        temper="passive", aggro=5, levels=[3, 40], stats=dict(hp=1300, atk=30, deff=45, spd=4.5, walk=2.0, stam=350, carry=650),
        abilities=["club_smash", "harvest", "shell_up"], passives=["fortress", "ore_finder"],
        tame=dict(method="knockout", difficulty=1.6, torpor=900), rideable=True, mount="ground",
        rider_weapons=["spear", "bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.38, 0.33, 0.26), belly=C(0.55, 0.5, 0.4), pattern=C(0.2, 0.18, 0.14), pt=4)],
        parts=[dict(id="armor", socket="back", size=1.0), dict(id="club", socket="tail_tip", size=1.3)],
        xp=150, loot=[["raw_meat", 3, 7], ["hide", 3, 6], ["keratin_plate", 2, 4], ["stone", 3, 8]],
        lore="Ein wandelnder Felsen. Seine Schwanzkeule bricht Erz aus dem Gestein – und Raubtieren die Beine.",
        sounds="grunt"),
    "brontosaurus": dict(
        name="Brontosaurus", rig="brontosaurus", family="quadruped", size="huge", diet="herbivore",
        food=["veggies"], biomes=["grassland", "swamp"], social="herd", temper="passive", aggro=0, levels=[10, 45],
        stats=dict(hp=4000, atk=55, deff=25, spd=4.5, walk=2.0, stam=600, carry=1600),
        abilities=["tail_swipe", "stomp", "harvest"], passives=["colossus", "pack_mule"],
        tame=dict(method="knockout", difficulty=3.5, torpor=2500), rideable=True, mount="ground", platform=True,
        rider_weapons=["bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.37, 0.36, 0.33), belly=C(0.55, 0.53, 0.48), pattern=C(0.27, 0.25, 0.22), pt=3)],
        parts=[], xp=480, loot=[["raw_meat", 10, 18], ["hide", 10, 18], ["large_bone", 4, 8]],
        lore="So groß, dass Bäume unter seinen Schritten brechen. Ein gezähmter Brontosaurus trägt ganze Lager.",
        sounds="bellow_deep"),
    "sarcosuchus": dict(
        name="Sarcosuchus", rig="sarcosuchus", family="crocodilian", size="large", diet="carnivore",
        food=["raw_fish", "raw_meat"], biomes=["swamp", "coast"], social="solitary", temper="ambusher",
        aggro=16, levels=[5, 35], stats=dict(hp=900, atk=48, deff=24, spd=5.5, walk=1.8, stam=300, carry=280, swim=8.5),
        abilities=["heavy_bite", "death_roll", "tail_swipe"], passives=["amphibious", "ambush"],
        tame=dict(method="knockout", difficulty=1.4, torpor=600), rideable=True, mount="amphibious",
        rider_weapons=["spear", "bow", "crossbow", "throw"],
        colors=[dict(main=C(0.24, 0.26, 0.18), belly=C(0.55, 0.52, 0.38), pattern=C(0.12, 0.14, 0.09), pt=3)],
        parts=[], xp=140, loot=[["raw_meat", 3, 6], ["hide", 4, 8], ["scales", 2, 4]],
        lore="Lauert regungslos im trüben Wasser. Die Todesrolle reißt selbst Raptoren in Stücke.", sounds="hiss_deep"),
    "direwolf": dict(
        name="Schreckenswolf", rig="direwolf", family="mammal", size="medium", diet="carnivore",
        food=["raw_meat", "raw_prime_meat"], biomes=["forest", "snow"], social="pack", temper="predator",
        aggro=28, levels=[1, 30], stats=dict(hp=220, atk=20, deff=8, spd=12.0, walk=2.8, stam=320, carry=130),
        abilities=["bite", "pack_call", "howl", "pounce"], passives=["pack_hunter", "scent_tracker", "cold_resist"],
        tame=dict(method="rescue", difficulty=1.0), rideable=True, mount="ground", min_ride_level=6,
        rider_weapons=["spear", "sword", "axe", "bow", "throw"],
        colors=[dict(main=C(0.32, 0.3, 0.28), belly=C(0.58, 0.55, 0.5), pattern=C(0.18, 0.17, 0.16), pt=4)],
        parts=[], tex="fur", xp=45, loot=[["raw_meat", 1, 3], ["pelt", 1, 2]],
        lore="Rudeltiere mit feinem Gespür. Ein verwundeter Wolf, dem man hilft, vergisst das nicht.", sounds="howl"),
    "smilodon": dict(
        name="Säbelzahnkatze", rig="smilodon", family="mammal", size="medium", diet="carnivore",
        food=["raw_meat", "raw_prime_meat"], biomes=["grassland", "snow", "forest"], social="solitary",
        temper="ambusher", aggro=24, levels=[3, 35], stats=dict(hp=300, atk=30, deff=10, spd=12.5, walk=2.8, stam=300, carry=150),
        abilities=["bite", "pounce", "saber_strike"], passives=["ambush", "cold_resist"],
        tame=dict(method="knockout", difficulty=1.2, torpor=350), rideable=True, mount="ground", min_ride_level=4,
        rider_weapons=["spear", "sword", "axe", "bow", "throw"],
        colors=[dict(main=C(0.6, 0.47, 0.32), belly=C(0.82, 0.75, 0.62), pattern=C(0.3, 0.22, 0.14), pt=2)],
        parts=[dict(id="fangs", socket="maw", size=0.38)], tex="fur", xp=70,
        loot=[["raw_meat", 2, 4], ["pelt", 1, 3], ["saber_fang", 0, 1]],
        lore="Ein Jäger aus dem Hinterhalt. Seine Säbelzähne reißen tiefe, blutende Wunden.", sounds="growl"),
    "mammoth": dict(
        name="Mammut", rig="mammoth", family="mammal", size="huge", diet="herbivore",
        food=["veggies", "berries"], biomes=["snow"], social="herd", temper="territorial", aggro=12, levels=[5, 40],
        stats=dict(hp=1600, atk=50, deff=26, spd=6.5, walk=2.4, stam=450, carry=800),
        abilities=["gore", "stomp", "trumpet", "harvest"], passives=["cold_resist", "lumberjack"],
        tame=dict(method="knockout", difficulty=2.0, torpor=1000), rideable=True, mount="ground",
        rider_weapons=["spear", "bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.33, 0.24, 0.17), belly=C(0.4, 0.3, 0.22), pattern=C(0.22, 0.15, 0.1), pt=4)],
        parts=[dict(id="tusks", socket="maw", size=0.9)], tex="fur", xp=200,
        loot=[["raw_meat", 5, 10], ["pelt", 4, 8], ["ivory", 1, 2]],
        lore="Die Riesen des Weißzahn-Gebirges. Mit ihren Stoßzähnen räumen sie Schnee und Bäume beiseite.",
        sounds="trumpet"),
    "pteranodon": dict(
        name="Pteranodon", rig="pteranodon", family="pterosaur", size="medium", diet="piscivore",
        food=["raw_fish", "raw_prime_fish"], biomes=["coast", "mountain"], social="flock", temper="skittish",
        aggro=4, levels=[1, 30], stats=dict(hp=250, atk=14, deff=5, spd=8.0, walk=2.0, stam=420, carry=110, fly=22.0),
        abilities=["bite", "dive", "wing_buffet"], passives=["flyer", "fisher"],
        tame=dict(method="trust", difficulty=1.5, feedings=4), rideable=True, mount="fly",
        rider_weapons=["bow", "throw"],
        colors=[dict(main=C(0.45, 0.42, 0.38), belly=C(0.78, 0.75, 0.7), pattern=C(0.65, 0.25, 0.12), pt=0)],
        parts=[dict(id="crest_ptera", socket="head_top", size=0.6)], xp=40,
        loot=[["raw_meat", 1, 2], ["hide", 1, 2], ["feather", 0, 1]],
        lore="Gleitet über Küsten und Klippen. Ein schneller, aber zerbrechlicher Flieger – ideal zum Erkunden.",
        sounds="caw"),
    "argentavis": dict(
        name="Argentavis", rig="argentavis", family="avian", size="large", diet="carnivore",
        food=["raw_meat", "raw_prime_meat"], biomes=["mountain", "grassland", "snow"], social="solitary",
        temper="territorial", aggro=16, levels=[5, 40], stats=dict(hp=380, atk=24, deff=8, spd=6.0, walk=2.0, stam=520, carry=260, fly=18.0),
        abilities=["bite", "dive", "grab", "wing_buffet"], passives=["flyer", "carrier"],
        tame=dict(method="knockout", difficulty=1.4, torpor=400), rideable=True, mount="fly",
        rider_weapons=["bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.28, 0.22, 0.17), belly=C(0.55, 0.47, 0.38), pattern=C(0.12, 0.1, 0.08), pt=0)],
        parts=[], xp=110, loot=[["raw_meat", 2, 4], ["feather", 3, 6]],
        lore="Ein gewaltiger Greifvogel. Trägt Lasten und kleinere Tiere über weite Strecken.", sounds="eagle"),
    "wyvern": dict(
        name="Wyvern", rig="wyvern", family="wyvern", size="huge", diet="carnivore",
        food=["raw_prime_meat", "wyvern_milk"], biomes=["volcano", "mountain"], social="solitary",
        temper="predator", aggro=40, levels=[20, 50],
        stats=dict(hp=1400, atk=60, deff=20, spd=8.0, walk=2.8, stam=600, carry=350, fly=21.0),
        abilities=["breath", "bite", "dive", "wing_buffet"], passives=["flyer", "elemental_core"],
        tame=dict(method="magic", difficulty=2.5, alt="egg"), rideable=True, mount="fly",
        rider_weapons=["bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.45, 0.17, 0.1), belly=C(0.7, 0.5, 0.3), pattern=C(0.15, 0.06, 0.04), pt=1)],
        parts=[dict(id="horns_demon", socket="head_top", size=0.65), dict(id="spikes_back", socket="back", size=0.6)],
        elements={"fire": 0.8}, xp=520, loot=[["raw_prime_meat", 4, 8], ["wyvern_scale", 3, 6], ["elemental_essence", 1, 2]],
        lore="Ein elementarer Drache der Vulkaninseln. Je nach Gelege speit er Feuer, Gift oder Blitze.",
        sounds="roar_dragon"),
    "mosasaurus": dict(
        name="Mosasaurus", rig="mosasaurus", family="marine", size="huge", diet="carnivore",
        food=["raw_prime_fish", "raw_prime_meat"], biomes=["deep_sea"], social="solitary", temper="predator",
        aggro=45, levels=[20, 50], stats=dict(hp=2200, atk=80, deff=22, spd=3.0, walk=1.0, stam=500, carry=700, swim=12.0),
        abilities=["heavy_bite", "tidal_slam", "tail_swipe"], passives=["aquatic", "deep_diver"],
        tame=dict(method="knockout", difficulty=3.0, torpor=1500), rideable=True, mount="swim",
        rider_weapons=["spear", "crossbow", "throw"],
        colors=[dict(main=C(0.2, 0.25, 0.28), belly=C(0.65, 0.66, 0.62), pattern=C(0.1, 0.12, 0.14), pt=0)],
        parts=[], xp=500, loot=[["raw_prime_fish", 6, 10], ["hide", 6, 10], ["scales", 4, 8]],
        lore="Der Schrecken der Tiefe. Kein Schwimmer überlebt lange, wo ein Mosasaurus jagt.", sounds="roar_water"),
    "plesiosaurus": dict(
        name="Plesiosaurus", rig="plesiosaurus", family="marine", size="large", diet="piscivore",
        food=["raw_fish", "raw_prime_fish"], biomes=["sea", "coast"], social="solitary", temper="passive",
        aggro=0, levels=[5, 40], stats=dict(hp=1100, atk=30, deff=15, spd=2.0, walk=1.0, stam=420, carry=450, swim=10.0),
        abilities=["bite", "sonar_pulse"], passives=["aquatic", "deep_diver", "air_bubble"],
        tame=dict(method="trust", difficulty=1.5, feedings=4), rideable=True, mount="swim",
        rider_weapons=["spear", "bow", "crossbow", "throw"],
        colors=[dict(main=C(0.25, 0.3, 0.3), belly=C(0.7, 0.7, 0.65), pattern=C(0.15, 0.2, 0.22), pt=2)],
        parts=[], xp=150, loot=[["raw_fish", 4, 8], ["hide", 3, 6]],
        lore="Sanfter Riese der Küstengewässer. Er schenkt seinem Reiter Luft unter Wasser.", sounds="whale"),
    "ichthyosaurus": dict(
        name="Ichthyosaurus", rig="ichthyosaurus", family="fish", size="medium", diet="piscivore",
        food=["raw_fish"], biomes=["sea", "coast"], social="pod", temper="curious", aggro=0, levels=[1, 30],
        stats=dict(hp=350, atk=14, deff=6, spd=1.0, walk=1.0, stam=420, carry=120, swim=16.0),
        abilities=["bite", "sprint_burst"], passives=["aquatic", "playful"],
        tame=dict(method="trust", difficulty=0.8, feedings=2), rideable=True, mount="swim",
        rider_weapons=["spear", "throw"],
        colors=[dict(main=C(0.3, 0.38, 0.45), belly=C(0.8, 0.82, 0.8), pattern=C(0.15, 0.2, 0.3), pt=0)],
        parts=[], xp=35, loot=[["raw_fish", 2, 4], ["hide", 1, 2]],
        lore="Verspielt und neugierig. Folgt Booten und Schwimmern gern.", sounds="click"),
    "megalodon": dict(
        name="Megalodon", rig="megalodon", family="fish", size="huge", diet="carnivore",
        food=["raw_prime_fish", "raw_prime_meat", "raw_fish"], biomes=["deep_sea", "sea"], social="pack",
        temper="predator", aggro=40, levels=[10, 45], stats=dict(hp=1500, atk=65, deff=12, spd=1.0, walk=1.0, stam=420, carry=450, swim=13.5),
        abilities=["heavy_bite", "frenzy"], passives=["aquatic", "blood_scent"],
        tame=dict(method="knockout", difficulty=2.2, torpor=800), rideable=True, mount="swim",
        rider_weapons=["spear", "crossbow", "throw"],
        colors=[dict(main=C(0.32, 0.36, 0.4), belly=C(0.82, 0.82, 0.8), pattern=C(0.2, 0.22, 0.25), pt=0)],
        parts=[], xp=300, loot=[["raw_prime_fish", 4, 8], ["shark_tooth", 2, 5]],
        lore="Gigantischer Hai der offenen See. Blut im Wasser lockt ganze Rudel an.", sounds="none"),
    "titanoboa": dict(
        name="Titanoboa", rig="titanoboa", family="serpent", size="large", diet="carnivore",
        food=["raw_meat", "raw_prime_meat"], biomes=["jungle", "swamp", "cave"], social="solitary",
        temper="ambusher", aggro=18, levels=[5, 35], stats=dict(hp=1000, atk=40, deff=14, spd=6.0, walk=2.0, stam=300, carry=200, swim=7.0),
        abilities=["bite", "constrict", "venom_bite"], passives=["amphibious", "ambush"],
        tame=dict(method="egg", difficulty=1.5), rideable=False, mount="",
        colors=[dict(main=C(0.25, 0.28, 0.16), belly=C(0.6, 0.55, 0.38), pattern=C(0.1, 0.1, 0.06), pt=2)],
        parts=[], xp=140, loot=[["raw_meat", 3, 6], ["scales", 3, 6], ["venom_gland", 0, 2]],
        lore="Eine Würgeschlange von der Länge eines Langhauses. Nistet in feuchten Höhlen.", sounds="hiss_deep"),
    "spider": dict(
        name="Höhlenspinne", rig="spider", family="arthropod", size="medium", diet="carnivore",
        food=["raw_meat"], biomes=["cave", "jungle"], social="solitary", temper="predator", aggro=22, levels=[3, 30],
        stats=dict(hp=400, atk=26, deff=14, spd=8.0, walk=2.5, stam=260, carry=150),
        abilities=["venom_bite", "web_shot"], passives=["wall_crawler", "venomous"],
        tame=dict(method="knockout", difficulty=1.6, torpor=400), rideable=True, mount="ground", min_ride_level=10,
        rider_weapons=["bow", "crossbow", "throw"],
        colors=[dict(main=C(0.12, 0.1, 0.09), belly=C(0.3, 0.2, 0.15), pattern=C(0.55, 0.15, 0.08), pt=2)],
        parts=[], xp=70, loot=[["chitin", 2, 4], ["silk", 2, 5], ["venom_gland", 0, 1]],
        lore="Jägt in völliger Dunkelheit. Ihre Seide ist ein begehrtes Handwerksmaterial.", sounds="hiss"),
    # ---------------------------------------------------------------- monsters
    "hellhound": dict(
        name="Höllenhund", rig="hellhound", family="mammal", size="medium", diet="carnivore",
        food=["raw_meat", "demon_heart"], biomes=["corrupted"], social="pack", temper="demonic", aggro=40,
        levels=[5, 40], stats=dict(hp=450, atk=34, deff=14, spd=12.0, walk=3.0, stam=360, carry=150),
        abilities=["bite", "hellfire_breath", "pounce", "howl"], passives=["demonic", "fire_immune"],
        tame=dict(method="pact", difficulty=1.5), rideable=True, mount="ground", min_ride_level=8, monster=True,
        rider_weapons=["spear", "sword", "axe", "bow", "throw"],
        colors=[dict(main=C(0.12, 0.08, 0.07), belly=C(0.25, 0.12, 0.1), pattern=C(0.4, 0.08, 0.05), pt=4)],
        parts=[dict(id="horns_demon", socket="head_top", size=0.45), dict(id="bone_spikes", socket="back", size=0.5)],
        corruption=0.9, glow=1.0, glow_color=C(1.0, 0.35, 0.05), elements={"fire": 0.7, "shadow": 0.3},
        tex="fur", xp=110, loot=[["demon_essence", 1, 2], ["charred_bone", 1, 3], ["pelt", 0, 1]],
        lore="Aus den Rissen gekrochene Bestien mit glühenden Adern. Riechen Furcht über Meilen.", sounds="growl_demon"),
    "shadowstalker": dict(
        name="Schattenpirscher", rig="shadowstalker", family="theropod", size="medium", diet="carnivore",
        food=["raw_meat", "demon_heart"], biomes=["corrupted"], social="solitary", temper="demonic", aggro=36,
        levels=[10, 45], stats=dict(hp=700, atk=42, deff=16, spd=13.0, walk=3.2, stam=380, carry=180),
        abilities=["slash_claw", "shadow_step", "pounce", "bite"], passives=["demonic", "night_hunter"],
        tame=dict(method="pact", difficulty=2.0), rideable=True, mount="ground", monster=True,
        rider_weapons=["spear", "sword", "axe", "throw"],
        colors=[dict(main=C(0.07, 0.06, 0.08), belly=C(0.15, 0.12, 0.16), pattern=C(0.25, 0.05, 0.3), pt=1)],
        parts=[dict(id="horns_ram", socket="head_top", size=0.5), dict(id="spikes_back", socket="back", size=0.55)],
        corruption=1.0, glow=0.8, glow_color=C(0.6, 0.2, 1.0), elements={"shadow": 0.8},
        xp=200, loot=[["demon_essence", 1, 3], ["shadow_shard", 0, 1]],
        lore="Ein Raubtier aus verdorbenem Fleisch, das zwischen den Schatten springt.", sounds="screech_demon"),
    "bonewyrm": dict(
        name="Knochenwyrm", rig="bonewyrm", family="serpent", size="huge", diet="carnivore",
        food=["demon_heart", "raw_prime_meat"], biomes=["corrupted", "cave"], social="solitary", temper="demonic",
        aggro=40, levels=[20, 50], stats=dict(hp=2000, atk=60, deff=30, spd=7.0, walk=2.0, stam=500, carry=400),
        abilities=["bite", "bone_storm", "constrict", "tail_swipe"], passives=["demonic", "burrower"],
        tame=dict(method="pact", difficulty=3.0), rideable=True, mount="ground", monster=True,
        rider_weapons=["bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.55, 0.5, 0.42), belly=C(0.4, 0.35, 0.3), pattern=C(0.2, 0.08, 0.06), pt=3)],
        parts=[dict(id="bone_spikes", socket="back", size=1.1), dict(id="bone_spikes", socket="back_front", size=1.0),
               dict(id="bone_spikes", socket="tail_mid", size=0.9), dict(id="horns_demon", socket="head_top", size=0.8)],
        corruption=0.7, glow=0.6, glow_color=C(0.9, 0.1, 0.05), elements={"blood": 0.6, "earth": 0.4},
        xp=420, loot=[["demon_essence", 2, 4], ["large_bone", 4, 8], ["blood_crystal", 0, 1]],
        lore="Ein Wurm aus verschmolzenen Knochen. Wo er sich eingräbt, versickert das Leben.", sounds="roar_demon"),
    "riftspider": dict(
        name="Rissweberin", rig="riftspider", family="arthropod", size="large", diet="carnivore",
        food=["demon_heart"], biomes=["corrupted", "cave"], social="solitary", temper="demonic", aggro=34,
        levels=[15, 45], stats=dict(hp=900, atk=44, deff=22, spd=8.5, walk=2.5, stam=400, carry=300),
        abilities=["venom_bite", "web_shot", "shadow_step"], passives=["demonic", "wall_crawler"],
        tame=dict(method="pact", difficulty=2.2), rideable=True, mount="ground", monster=True,
        rider_weapons=["bow", "crossbow", "throw", "staff"],
        colors=[dict(main=C(0.1, 0.06, 0.1), belly=C(0.25, 0.1, 0.2), pattern=C(0.8, 0.15, 0.5), pt=2)],
        parts=[dict(id="bone_spikes", socket="back", size=0.8)], corruption=1.0, glow=1.0,
        glow_color=C(0.9, 0.2, 0.8), elements={"shadow": 0.6, "poison": 0.4},
        xp=260, loot=[["demon_essence", 2, 3], ["silk", 3, 6], ["rift_shard", 0, 1]],
        lore="Webt Netze zwischen den Welten. Ihre Fäden glühen im Rhythmus der Risse.", sounds="hiss_demon"),
}

# Story/boss variants (not tameable)
BOSSES = {
    "gorrath": dict(base="trex", name="Gorrath, der Verderbte", level=30, hp_mult=3.5, atk_mult=1.4, scale=1.3,
                    corruption=1.0, glow=1.0, glow_color=C(1.0, 0.25, 0.05), elements={"fire": 0.5, "shadow": 0.5},
                    parts=[dict(id="bone_spikes", socket="back", size=1.4), dict(id="horns_demon", socket="head_top", size=0.9)],
                    abilities=["heavy_bite", "roar", "tail_swipe", "hellfire_breath"], tameable=False),
    "alpha_raptor": dict(base="raptor", name="Narbenklaue", level=15, hp_mult=3.0, atk_mult=1.5, scale=1.3,
                         corruption=0.0, tameable=False, abilities=["bite", "pounce", "pack_call", "slash_claw"]),
}

# Humanoid rigs used by NPCs/player (not species)
HUMANOIDS = {
    "human_m": dict(rig="human_m"), "human_f": dict(rig="human_f"),
    "goblin": dict(rig="goblin"), "demon": dict(rig="demon"),
}
