# Factions, NPCs, quests, dialogues (German). Conditions/actions use a tiny DSL interpreted by Dialogue.gd:
# cond:  quest:<id>=<state>|stage:<id>>=<n>|flag:<k>|!flag:<k>|rep:<f>>=<n>|item:<id>>=<n>|amber>=<n>|demon_form|demon_unlocked|research:<id>
# action: start:<qid> | advance:<qid> | complete:<qid> | give:<item>:<n> | take:<item>:<n> | amber:<n> | rep:<f>:<n>
#         flag:<k>=<v> | research:<id> | trade | teach:<research> | path:<p>:<n> | respec | end | goto:<node> | xp:<n>

FACTIONS = {
    "morgengrau": dict(name="Siedler von Morgengrau", desc="Gestrandete Menschen, Fischer und Gelehrte. Vorsichtig, aber hilfsbereit.",
                       demon_reaction="hostile", color=[0.8, 0.7, 0.4]),
    "moosfell": dict(name="Moosfell-Goblins", desc="Händler und Kräuterkundige aus dem Dschungel. Fürchten die Rissbrut.",
                     demon_reaction="flee", color=[0.35, 0.6, 0.3]),
    "knochenbrecher": dict(name="Knochenbrecher-Stamm", desc="Kriegerische Goblins der Ebene. Respektieren nur Stärke.",
                           demon_reaction="respect", color=[0.7, 0.3, 0.2]),
    "daemonengoblins": dict(name="Rissbrut", desc="Vom Riss verdorbene Goblins unter dem Propheten Vashrak.",
                            demon_reaction="ally", color=[0.5, 0.1, 0.2]),
    "eisenhand": dict(name="Eisenhand-Söldner", desc="Söldner vom Festland unter Hauptmann Brannoc. Wollen die Inseln beherrschen.",
                      demon_reaction="hostile", color=[0.45, 0.45, 0.5]),
}

NPCS = {
    "ilsa": dict(name="Ilsa Varn", faction="morgengrau", rig="human_f", poi="morgengrau", offset=[4, 0, -3], role="Kräuterkundige & Forscherin",
                 colors=dict(top_color=[0.28, 0.32, 0.25], bottom_color=[0.25, 0.2, 0.15], hair_color=[0.55, 0.5, 0.45]),
                 bio="Leitet Morgengrau seit dem Verschwinden ihres Bruders Ewald. Sucht nach einer Möglichkeit, den Riss zu schließen.",
                 trades=["herb_healing", "bandage", "healing_salve", "research_notes", "creature_medicine", "kibble"], teaches=["veterinary", "genetics_1"]),
    "tomas": dict(name="Tomas Kessler", faction="morgengrau", rig="human_m", poi="morgengrau", offset=[-6, 0, 2], role="Schmied",
                  colors=dict(top_color=[0.2, 0.18, 0.16], bottom_color=[0.2, 0.17, 0.14], hair_color=[0.1, 0.08, 0.06]),
                  bio="Ehemaliger Schiffsschmied. Ohne Erz kann er nichts schmieden.",
                  trades=["metal_ingot", "arrow_stone", "spear_stone", "axe_stone", "pick_stone", "saddle_small"], teaches=["metallurgy"]),
    "grukk": dict(name="Häuptling Grukk", faction="moosfell", rig="goblin", poi="moosfell", offset=[3, 0, 0], role="Häuptling der Moosfell",
                  colors=dict(color_main=[0.32, 0.42, 0.24], top_color=[0.3, 0.25, 0.15], bottom_color=[0.25, 0.2, 0.12]),
                  bio="Alt, listig und misstrauisch gegenüber Menschen. Seine Jäger verschwinden im Moor.", trades=["berries", "veggies", "rare_flower", "fiber", "hide", "narcoberry", "venom_gland"]),
    "nixa": dict(name="Nixa Moosauge", faction="moosfell", rig="goblin", poi="moosfell", offset=[-5, 0, 4], role="Schamanin",
                 colors=dict(color_main=[0.38, 0.45, 0.3], top_color=[0.2, 0.3, 0.35], bottom_color=[0.15, 0.2, 0.2]),
                 bio="Spürt die Elemente in jedem Lebewesen. Hält Vashrak für ihren gescheiterten Schüler.",
                 trades=["elemental_essence", "crystal", "narcotic", "antidote", "binding_rune"], teaches=["element_theory", "binding_magic"]),
    "skarza": dict(name="Skarza Blutzahn", faction="knochenbrecher", rig="goblin", poi="knochenbrecher", offset=[0, 0, -6], role="Kriegshäuptling",
                   colors=dict(color_main=[0.42, 0.36, 0.22], top_color=[0.45, 0.15, 0.1], bottom_color=[0.25, 0.15, 0.1]),
                   bio="Hat den Bannschlüssel des Narbenschlunds an sich gerissen. Respektiert nur Stärke – oder Bernstein.", boss_scale=1.25,
                   trades=["large_bone", "horn", "raptor_claw", "javelin", "bola"]),
    "brannoc": dict(name="Hauptmann Brannoc Eisenhand", faction="eisenhand", rig="human_m", poi="fischerkap", offset=[3, 0, 3], role="Söldnerführer",
                    colors=dict(top_color=[0.4, 0.4, 0.42], bottom_color=[0.18, 0.16, 0.15], hair_color=[0.3, 0.22, 0.12]),
                    bio="Kam mit drei Schiffen und dem Auftrag, die Inseln für die Krone zu sichern. Sieht im Riss eine Waffe.",
                    trades=["metal_ingot", "crossbow", "bolt_metal", "gunpowder", "shot_iron", "armor_metal_chest"], teaches=["black_powder"]),
    "vashrak": dict(name="Vashrak der Rissprophet", faction="daemonengoblins", rig="goblin", poi="riss_narbenschlund", offset=[0, 0, 0], role="Prophet der Rissbrut",
                    colors=dict(color_main=[0.28, 0.12, 0.14], top_color=[0.2, 0.05, 0.08], bottom_color=[0.1, 0.05, 0.05]), corruption=0.9,
                    bio="Ein verstoßener Moosfell-Schamane, der dem Flüstern aus dem Riss verfiel.", hostile=True, boss_scale=1.3),
    "zibbel": dict(name="Zibbel", faction="moosfell", rig="goblin", poi="teergrube", offset=[10, 0, 6], role="Moosfell-Jäger",
                   colors=dict(color_main=[0.35, 0.4, 0.25], top_color=[0.35, 0.3, 0.2], bottom_color=[0.3, 0.25, 0.15]),
                   bio="Wurde von Höllenhunden in die Enge getrieben.", hidden_until="q4_moosfell"),
}

# generic population (not unique)
NPCS.update({
    "siedler": dict(name="Siedler", faction="morgengrau", rig="human_m", role="Morgengrau", generic=True,
                    colors=dict(top_color=[0.4, 0.35, 0.28], bottom_color=[0.28, 0.24, 0.2], hair_color=[0.25, 0.18, 0.1])),
    "siedlerin": dict(name="Siedlerin", faction="morgengrau", rig="human_f", role="Morgengrau", generic=True,
                      colors=dict(top_color=[0.35, 0.3, 0.32], bottom_color=[0.3, 0.25, 0.2], hair_color=[0.45, 0.3, 0.15])),
    "moosfell_goblin": dict(name="Moosfell-Goblin", faction="moosfell", rig="goblin", role="Moosfell", generic=True,
                            colors=dict(color_main=[0.33, 0.43, 0.25], top_color=[0.35, 0.28, 0.18], bottom_color=[0.28, 0.22, 0.14])),
    "knochenbrecher_krieger": dict(name="Knochenbrecher", faction="knochenbrecher", rig="goblin", role="Krieger", generic=True, weapon="club", level=10,
                                   colors=dict(color_main=[0.42, 0.38, 0.24], top_color=[0.5, 0.18, 0.12], bottom_color=[0.25, 0.15, 0.1])),
    "soeldner": dict(name="Söldner", faction="eisenhand", rig="human_m", role="Eisenhand", generic=True, weapon="spear", level=14,
                     colors=dict(top_color=[0.45, 0.45, 0.48], bottom_color=[0.2, 0.18, 0.16], hair_color=[0.2, 0.15, 0.1])),
    "rissbrut": dict(name="Rissbrut-Goblin", faction="daemonengoblins", rig="goblin", role="", generic=True, hostile=True, weapon="spear", level=14, corruption=0.8,
                     colors=dict(color_main=[0.3, 0.12, 0.14], top_color=[0.15, 0.05, 0.06], bottom_color=[0.1, 0.04, 0.05]),
                     parts=[dict(id="horns_short", socket="head_top", size=0.25)]),
    "herold": dict(name="Herold Azh'Moraths", faction="daemonengoblins", rig="demon", role="", hostile=True, boss_scale=1.6, level=45, hp=6000, atk=90, corruption=1.0,
                   colors=dict(color_main=[0.15, 0.04, 0.05], top_color=[0.15, 0.04, 0.05], bottom_color=[0.08, 0.02, 0.02]),
                   parts=[dict(id="horns_demon", socket="head_top", size=0.7), dict(id="tail_demon", socket="tail_tip", size=1.0)]),
})
NPCS["vashrak"]["weapon"] = "staff"
NPCS["vashrak"]["level"] = 26
NPCS["vashrak"]["hp"] = 1400
NPCS["vashrak"]["atk"] = 45
NPCS["skarza"]["weapon"] = "club"
NPCS["skarza"]["level"] = 20
NPCS["skarza"]["hp"] = 1100
NPCS["skarza"]["atk"] = 38

Q = lambda **kw: kw

QUESTS = {
    "q1_gestrandet": Q(name="Gestrandet", act=1, giver="", main=True,
                       desc="Ein Mosasaurus hat dein Schiff zerschmettert. Du bist allein am Treibgutstrand der Insel Grünkrone gestrandet.",
                       stages=[
                           dict(text="Sammle Holz, Stein und Fasern (Bäume, Steine und Büsche mit E oder Werkzeug bearbeiten).",
                                obj=[dict(type="have", item="wood", n=6), dict(type="have", item="stone", n=6), dict(type="have", item="fiber", n=10)]),
                           dict(text="Baue ein Lagerfeuer (Baumodus: B) und brate rohes Fleisch oder Fisch daran.",
                                obj=[dict(type="build", what="campfire", n=1), dict(type="craft", item="cooked_meat|cooked_fish", n=1)]),
                           dict(text="Rauch steigt im Westen auf. Folge dem Pfad zur Siedlung Morgengrau.",
                                obj=[dict(type="visit", poi="morgengrau")]),
                       ],
                       rewards=dict(xp=80, amber=10), next=["q2_zuflucht"]),
    "q2_zuflucht": Q(name="Zuflucht", act=1, giver="ilsa", main=True,
                     desc="Ilsa Varn, die Anführerin von Morgengrau, braucht einen Bestienbändiger. Beweise, dass du einer bist.",
                     stages=[
                         dict(text="Sprich mit Ilsa Varn in Morgengrau.", obj=[dict(type="talk", npc="ilsa")]),
                         dict(text="Gewinne deinen ersten Gefährten. Ilsa rät: Gallimimus und Parasaurolophus vertrauen dir, wenn du dich geduckt näherst und Beeren anbietest. Raubtiere lassen sich mit Keule oder Betäubungspfeilen bezwingen.",
                              obj=[dict(type="tame", species="any", n=1)]),
                         dict(text="Kehre mit deinem Gefährten zu Ilsa zurück.", obj=[dict(type="talk", npc="ilsa")]),
                     ],
                     rewards=dict(xp=150, items=[["soul_crystal", 1], ["kibble", 4]], research_points=3, rep=[["morgengrau", 10]]), next=["q3_lager"]),
    "q3_lager": Q(name="Ein eigenes Lager", act=1, giver="ilsa", main=True,
                  desc="Morgengrau ist zu klein für deine Bestien. Errichte ein eigenes Lager.",
                  stages=[
                      dict(text="Errichte einen Lagerstein (Baumodus) an einem Ort deiner Wahl – nicht in Siedlungen.",
                           obj=[dict(type="build", what="camp_totem", n=1)]),
                      dict(text="Baue Schlaflager, Werkbank und ein Gehege im Lager.",
                           obj=[dict(type="build", what="bedroll|bed", n=1), dict(type="build", what="workbench", n=1), dict(type="build", what="pen", n=1)]),
                      dict(text="Berichte Ilsa von deinem Lager.", obj=[dict(type="talk", npc="ilsa")]),
                  ],
                  rewards=dict(xp=200, amber=30, research_points=4), next=["q4_moosfell"]),
    "q4_moosfell": Q(name="Die Moosfell", act=1, giver="ilsa", main=True,
                     desc="Die Moosfell-Goblins im Osten kennen das Moor besser als jeder Mensch. Ilsa braucht ihre Hilfe – aber Häuptling Grukk traut keinem Menschen.",
                     stages=[
                         dict(text="Reise ins Moosfell-Dorf im Smaragddschungel und sprich mit Häuptling Grukk.", obj=[dict(type="talk", npc="grukk")]),
                         dict(text="Rette den Jäger Zibbel bei der Teergrube: Vertreibe die Höllenhunde, die ihn umzingelt haben.",
                              obj=[dict(type="kill", tag="hellhound", n=3, at="teergrube")]),
                         dict(text="Sprich mit Zibbel bei der Teergrube.", obj=[dict(type="talk", npc="zibbel")]),
                         dict(text="Bringe Grukk die Nachricht von Zibbels Rettung.", obj=[dict(type="talk", npc="grukk")]),
                     ],
                     rewards=dict(xp=300, amber=40, rep=[["moosfell", 25]], items=[["grukk_totem", 1]]), next=["q5_spuren"]),
    "q5_spuren": Q(name="Spuren des Risses", act=1, giver="ilsa", main=True,
                   desc="Die Höllenhunde kamen aus dem Nordwesten. Ilsa will verstehen, was dort geschieht.",
                   stages=[
                       dict(text="Sammle 3 Risssplitter im Narbenschlund (von Rissbestien oder Risskristallen).", obj=[dict(type="have", item="rift_shard", n=3)]),
                       dict(text="Untersuche die Alte Warte im Flüsterwald – Ewald soll dort geforscht haben.", obj=[dict(type="visit", poi="alte_warte")]),
                       dict(text="Erforsche „Rissanalyse“ an einem Forschungstisch.", obj=[dict(type="research", id="rift_analysis")]),
                       dict(text="Sprich mit Ilsa über deine Erkenntnisse.", obj=[dict(type="talk", npc="ilsa")]),
                   ],
                   rewards=dict(xp=350, research_points=6, research=["crystal_2"]), next=["q6_blut"]),
    "q6_blut": Q(name="Blut und Gene", act=1, giver="ilsa", main=True,
                 desc="Der Riss ist durch einen Bann geschützt, den nur eine außergewöhnliche Kreatur brechen kann. Ilsa lehrt dich die alte Kunst der Kreuzung.",
                 stages=[
                     dict(text="Baue ein Genlabor in deinem Lager.", obj=[dict(type="build", what="gene_lab", n=1)]),
                     dict(text="Erschaffe deinen ersten Hybriden im Genlabor und brüte ihn aus.", obj=[dict(type="hybrid", n=1)]),
                     dict(text="Zeige Ilsa deine Schöpfung.", obj=[dict(type="talk", npc="ilsa")]),
                 ],
                 rewards=dict(xp=400, research=["genetics_2"], amber=50), next=["q7_pakt"], on_start_research=["genetics_1"]),
    "q7_pakt": Q(name="Der Bannschlüssel", act=1, giver="ilsa", main=True,
                 desc="Das Siegel des Narbenschlunds öffnet nur der Bannschlüssel. Skarza Blutzahn, Häuptling der Knochenbrecher, hat ihn an sich gerissen.",
                 stages=[
                     dict(text="Finde Skarza im Knochenbrecher-Lager auf der Knochenebene und beschaffe den Bannschlüssel – mit Handel, Diplomatie, Gewalt oder … anderen Mitteln.",
                          obj=[dict(type="have", item="ward_key", n=1)]),
                 ],
                 rewards=dict(xp=450), next=["q8_herz"]),
    "q8_herz": Q(name="Das Herz des Risses", act=1, giver="ilsa", main=True,
                 desc="Mit dem Bannschlüssel kannst du in den Narbenschlund vordringen. Dort wartet Vashrak – und etwas Größeres.",
                 stages=[
                     dict(text="Öffne das Siegel im Narbenschlund mit dem Bannschlüssel.", obj=[dict(type="flag", flag="seal_opened")]),
                     dict(text="Besiege Vashrak den Rissprophet.", obj=[dict(type="kill", tag="vashrak", n=1)]),
                     dict(text="Besiege Gorrath, den Verderbten.", obj=[dict(type="kill", tag="gorrath", n=1)]),
                     dict(text="Entscheide am Herz des Risses über sein Schicksal.", obj=[dict(type="flag", flag="rift_choice")]),
                 ],
                 rewards=dict(xp=1200, amber=200, research_points=12), next=["q9_aschenkamm"]),
    # ---- act 2 (shorter)
    "q9_aschenkamm": Q(name="Feuer über dem Meer", act=2, giver="ilsa", main=True,
                       desc="Der Narbenschlund war nicht der einzige Riss. Über dem Vulkan Aschenkamm brennt der Himmel rot, und Brannocs Söldner sammeln sich am Fischerkap.",
                       stages=[
                           dict(text="Sprich mit Hauptmann Brannoc am Fischerkap.", obj=[dict(type="talk", npc="brannoc")]),
                           dict(text="Erreiche den Aschenkamm (Flug- oder Seereittier nötig) und finde den Wyvernhorst.", obj=[dict(type="visit", poi="wyvern_nest")]),
                           dict(text="Gewinne eine Wyvern – durch ein Ei, eine Bindungsrune oder rohe Gewalt.", obj=[dict(type="tame", species="wyvern", n=1)]),
                       ],
                       rewards=dict(xp=1500, amber=150), next=["q10_narbe"]),
    "q10_narbe": Q(name="Die Narbe", act=3, giver="ilsa", main=True,
                   desc="Alle Spuren führen zur Zitadelle auf der Narbe, wo Azh'Morath durch den letzten Riss greift.",
                   stages=[
                       dict(text="Erreiche die Zitadelle der Narbe.", obj=[dict(type="visit", poi="narbe_zitadelle")]),
                       dict(text="Besiege den Herold Azh'Moraths.", obj=[dict(type="kill", tag="herald", n=1)]),
                       dict(text="Triff deine letzte Entscheidung.", obj=[dict(type="flag", flag="final_choice")]),
                   ],
                   rewards=dict(xp=3000)),
    # ---- side quests
    "sq_raptor_ei": Q(name="Diebesgut", act=1, giver="ilsa", desc="Velociraptoren lassen sich nur von Geburt an prägen. Stiehl ein Ei aus einem Raptorennest und brüte es aus.",
                      stages=[dict(text="Stiehl ein Raptorenei aus einem Nest (Vorsicht – die Eltern bewachen es).", obj=[dict(type="have", item="egg", n=1)]),
                              dict(text="Brüte das Ei in einer Brutstätte aus.", obj=[dict(type="hatch", n=1)])],
                      rewards=dict(xp=250, items=[["kibble", 6]])),
    "sq_teer": Q(name="Gefangen im Teer", act=1, giver="", desc="Ein Stegosaurus steckt in der Teergrube fest. Raubtiere kreisen.",
                 stages=[dict(text="Befreie den Stegosaurus in der Teergrube: Vertreibe die Raubtiere und ziehe ihn heraus (E).", obj=[dict(type="flag", flag="stego_rescued")])],
                 rewards=dict(xp=200)),
    "sq_wolf": Q(name="Der verwundete Wolf", act=1, giver="", desc="In der Wolfsschlucht jault ein Schreckenswolf in einer Fußfalle der Knochenbrecher.",
                 stages=[dict(text="Befreie den Wolf (E) und versorge seine Wunde mit einem Verband.", obj=[dict(type="flag", flag="wolf_rescued")])],
                 rewards=dict(xp=200, rep=[["knochenbrecher", -5]])),
    "sq_tomas_erz": Q(name="Erz für die Esse", act=1, giver="tomas", desc="Tomas braucht Metallerz aus dem Nordgrat, um wieder schmieden zu können.",
                      stages=[dict(text="Bringe Tomas 10 Metallerz.", obj=[dict(type="deliver", item="metal_ore", n=10, npc="tomas")])],
                      rewards=dict(xp=200, research=["metallurgy"], rep=[["morgengrau", 10]])),
    "sq_nixa_blueten": Q(name="Blüten für die Schamanin", act=1, giver="nixa", desc="Nixa lehrt dich die Sprache der Elemente – gegen drei seltene Blüten.",
                         stages=[dict(text="Bringe Nixa 3 seltene Blüten.", obj=[dict(type="deliver", item="rare_flower", n=3, npc="nixa")])],
                         rewards=dict(xp=200, research=["element_theory"], skill_points=1, rep=[["moosfell", 10]], flags=["elemental_taught"])),
    "sq_ewald": Q(name="Ewalds Aufzeichnungen", act=1, giver="", desc="Verstreute Tagebuchseiten von Ilsas Bruder Ewald. Was hat er im Narbenschlund gesucht?",
                  stages=[dict(text="Finde Ewalds Tagebuchseiten (Alte Warte, Teergrube, Adlerhorst).", obj=[dict(type="have", item="journal_page_1", n=1), dict(type="have", item="journal_page_2", n=1), dict(type="have", item="journal_page_3", n=1)])],
                  rewards=dict(xp=300, research_points=4)),
}

DIALOGUES = {
    "ilsa": {
        "start": dict(text="Ein Überlebender? Bei den Ahnen … Ich bin Ilsa Varn. Morgengrau ist nicht viel, aber hier bist du sicher – solange die Palisade hält.",
                      options=[
                          dict(text="Mein Schiff wurde von einem Seeungeheuer zerstört.", goto="ship", cond="stage:q2_zuflucht=0"),
                          dict(text="Gibt es sonst etwas zu tun?", goto="side", cond="quest:q3_lager=active;!quest:sq_raptor_ei"),
                          dict(text="Ich habe einen Gefährten gewonnen.", action="advance:q2_zuflucht", cond="stage:q2_zuflucht>=2", goto="tamed"),
                          dict(text="Mein Lager steht.", action="advance:q3_lager", cond="stage:q3_lager>=2", goto="camp"),
                          dict(text="Ich habe die Risssplitter untersucht.", action="advance:q5_spuren", cond="stage:q5_spuren>=3", goto="rift"),
                          dict(text="Sieh dir meinen Hybriden an.", action="advance:q6_blut", cond="stage:q6_blut>=2", goto="hybrid"),
                          dict(text="Erzähl mir von Ewald.", goto="ewald"),
                          dict(text="Was weißt du über den Riss?", goto="riftlore"),
                          dict(text="Lass uns handeln.", action="trade"),
                          dict(text="Kannst du mich etwas lehren?", goto="teach"),
                          dict(text="Ich möchte meine Fähigkeiten neu ordnen. (Kosten in Bernstein)", action="respec"),
                          dict(text="Leb wohl.", action="end"),
                      ]),
        "ship": dict(text="Ein Mosasaurus. Sie jagen in der Tiefsee zwischen den Inseln – deshalb sitzen wir hier fest. Du sagst, du bist Bestienbändiger? Dann beweise es: Gewinne das Vertrauen eines Tieres. Kehr mit einem Gefährten zurück, dann reden wir weiter.",
                     options=[dict(text="Wie zähme ich ein Tier?", goto="howtame"), dict(text="Verstanden.", action="advance:q2_zuflucht;end")]),
        "howtame": dict(text="Jede Art ist anders. Pflanzenfresser wie Gallimimus oder Parasaurolophus: geduckt nähern (Strg), langsam, und Beeren anbieten (E). Raubtiere schlägst du mit der Keule oder Betäubungspfeilen bewusstlos und fütterst sie dann mit Fleisch. Velociraptoren nur aus dem Ei. Und manche Tiere … musst du retten.",
                        options=[dict(text="Danke.", action="advance:q2_zuflucht;end")]),
        "tamed": dict(text="Er folgt dir wirklich! Gut. Nimm diesen Seelenkristall – er stammt aus Ewalds Werkstatt. Darin kannst du Gefährten verwahren und rufen. Aber vergiss nie: Tod und Wunden hebt der Kristall nicht auf. Du brauchst ein eigenes Lager. Morgengrau hat keinen Platz für Bestien.",
                      options=[dict(text="Ich baue ein Lager.", action="end")]),
        "camp": dict(text="Ein Lagerstein, Gehege, eine Werkbank … du meinst es ernst. Dann hör zu: Die Moosfell-Goblins im Osten kennen das Moor. Seit Wochen verschwinden ihre Jäger. Wenn wir den Riss verstehen wollen, brauchen wir sie. Häuptling Grukk spricht aber nicht mit Menschen – vielleicht mit dir.",
                     options=[dict(text="Ich gehe zu den Moosfell.", action="end")]),
        "rift": dict(text="Diese Splitter … sie pulsieren wie ein Herz. Ewald hat genau so etwas beschrieben, bevor er verschwand. Der Riss ist durch einen alten Bann versiegelt – ein Bann, den nur eine Kreatur durchdringen kann, die zwei Naturen in sich trägt. Ich lehre dich die Kunst der Kreuzung. Baue ein Genlabor.",
                     options=[dict(text="Zwei Naturen?", goto="twonatures"), dict(text="Ich baue das Labor.", action="end")]),
        "twonatures": dict(text="Hybriden. Die Vorfahren dieser Inseln kreuzten Bestien, um gegen die Dämonen der alten Zeit zu bestehen. Sei vorsichtig: Je fremder die Körper, desto instabiler das Blut.",
                           options=[dict(text="Verstanden.", action="end")]),
        "hybrid": dict(text="Unglaublich … Ewald wäre stolz – oder entsetzt. Jetzt fehlt nur der Bannschlüssel. Skarza Blutzahn, der Häuptling der Knochenbrecher, hat ihn den Wächtern abgenommen. Bring ihn mir – wie, überlasse ich dir. Aber Blut zieht weiteres Blut nach sich.",
                       options=[dict(text="Ich hole den Schlüssel.", action="end")]),
        "side": dict(text="Velociraptoren. Sie sind klug – zu klug, um sie als Erwachsene zu zähmen. Aber ein Ei … ein frisch geschlüpfter Raptor prägt sich auf den Ersten, den er sieht. Im Morgengrauwald liegen Nester. Sei vorsichtig.",
                     options=[dict(text="Ich hole ein Ei.", action="start:sq_raptor_ei;end")]),
        "ewald": dict(text="Mein Bruder war Gelehrter. Er glaubte, die Macht der Vorfahren könne uns vor den Bestien schützen. Vor drei Jahren ging er in den Narbenschlund … in der Nacht, als sich der Himmel rot färbte. Seitdem kommen die Monster.",
                      options=[dict(text="Ich werde herausfinden, was geschah.", action="end"), dict(text="Zurück.", goto="start")]),
        "riftlore": dict(text="Die Moosfell nennen ihn „die Wunde“. Wer zu lange hinsieht, hört eine Stimme. Manche sagen, sie verspricht Macht. Ich sage: Sie lügt.",
                         options=[dict(text="Zurück.", goto="start")]),
        "teach": dict(text="Ich kann dir Tierheilkunde beibringen. Und wenn du bereit bist, die Grundlagen der Genetik.",
                      options=[dict(text="Tierheilkunde lernen.", action="teach:veterinary", goto="start"),
                               dict(text="Genetik lernen.", action="teach:genetics_1", cond="stage:q6_blut>=0", goto="start"),
                               dict(text="Zurück.", goto="start")]),
    },
    "tomas": {
        "start": dict(text="Hm? Noch so ein Strandgut. Ich bin Tomas. Schmied, wenn ich Erz hätte. Habe ich aber nicht.",
                      options=[
                          dict(text="Ich bringe dir Erz.", action="start:sq_tomas_erz", cond="!quest:sq_tomas_erz", goto="ore"),
                          dict(text="Hier ist dein Erz. (10 Metallerz)", action="take:metal_ore:10;advance:sq_tomas_erz", cond="quest:sq_tomas_erz=active;item:metal_ore>=10", goto="thanks"),
                          dict(text="Zeig mir deine Waren.", action="trade"),
                          dict(text="Leb wohl.", action="end"),
                      ]),
        "ore": dict(text="Im Nordgrat gibt es dunkle Adern im Fels – Metallerz. Nimm eine Spitzhacke. Zehn Brocken, dann bringe ich dir bei, wie man eine Schmiede baut.",
                    options=[dict(text="Abgemacht.", action="end")]),
        "thanks": dict(text="Ha! Das ist gutes Erz. Hör zu, so baust du eine Esse …", options=[dict(text="Danke.", action="end")]),
    },
    "grukk": {
        "start": dict(text="Mensch. Riecht nach Salz und Angst. Was willst du im Dorf von Grukk?",
                      options=[
                          dict(text="Ilsa Varn schickt mich. Wir wollen gegen den Riss kämpfen.", action="advance:q4_moosfell", cond="stage:q4_moosfell=0", goto="hunters"),
                          dict(text="Zibbel ist gerettet.", action="advance:q4_moosfell", cond="stage:q4_moosfell=3", goto="thanks"),
                          dict(text="Sprichst du für mich bei den Knochenbrechern?", cond="quest:q7_pakt=active;rep:moosfell>=50;!flag:grukk_mediated", goto="mediate"),
                          dict(text="Handeln.", action="trade", cond="rep:moosfell>=0"),
                          dict(text="Gehen.", action="end"),
                      ]),
        "hunters": dict(text="Ilsa. Die Kräuterfrau. Grukk mag sie. Hör zu, Mensch: Zibbel, mein bester Jäger, ist zur Teergrube gegangen. Dann kamen die Feuerhunde. Bring Zibbel zurück, dann redet Grukk mit dir.",
                        options=[dict(text="Ich finde ihn.", action="end")]),
        "thanks": dict(text="Zibbel lebt! Grukk vergisst das nicht. Nimm das Totem – die Moosfell erkennen dich jetzt als Freund. Und sag Ilsa: Die Feuerhunde kommen aus der Wunde im Nordwesten.",
                       options=[dict(text="Danke, Häuptling.", action="end")]),
        "mediate": dict(text="Skarza ist ein Schädelbrecher, aber er schuldet Grukk drei Ziegen und einen Bruder. Grukk schickt Bote. Skarza wird mit dir reden – und den Schlüssel gegen Frieden tauschen.",
                        options=[dict(text="Danke.", action="flag:grukk_mediated=1;rep:knochenbrecher:30;end")]),
    },
    "nixa": {
        "start": dict(text="Du trägst Feuer und Erde in dir … und etwas Dunkles, das schläft. Ich bin Nixa.",
                      options=[
                          dict(text="Lehre mich die Elemente.", action="start:sq_nixa_blueten", cond="!quest:sq_nixa_blueten", goto="flowers"),
                          dict(text="Hier sind drei seltene Blüten.", action="take:rare_flower:3;advance:sq_nixa_blueten", cond="quest:sq_nixa_blueten=active;item:rare_flower>=3", goto="taught"),
                          dict(text="Kannst du mich Bindungsmagie lehren?", action="teach:binding_magic", cond="rep:moosfell>=25"),
                          dict(text="Was meinst du mit „etwas Dunkles“?", goto="dark"),
                          dict(text="Handeln.", action="trade"),
                          dict(text="Leb wohl.", action="end"),
                      ]),
        "flowers": dict(text="Drei seltene Blüten. Sie wachsen im Schatten großer Bäume. Bring sie mir, dann öffne ich dir die Augen.",
                        options=[dict(text="Ich bringe sie.", action="end")]),
        "taught": dict(text="Schließe die Augen. Spürst du die Wärme des Feuers? Das Ziehen der Erde? Jedes Wesen trägt bis zu fünf Elemente. Lerne, sie zu lenken.",
                       options=[dict(text="Ich spüre es.", action="end")]),
        "dark": dict(text="Jeder trägt einen Schatten. Ewald fand einen Weg, seinen zu wecken. Der Gehörnte im Moor kennt das Ritual. Aber ich rate dir: Lass ihn schlafen.",
                     options=[dict(text="Der Gehörnte?", goto="horned"), dict(text="Zurück.", goto="start")]),
        "horned": dict(text="Ein Schrein, älter als mein Volk, tief im Moorkessel. Ewald ging oft dorthin. Nachts, wenn die Stimme am lautesten ist.",
                       options=[dict(text="Zurück.", goto="start")]),
    },
    "skarza": {
        "start": dict(text="HA! Ein Menschlein im Lager der Knochenbrecher. Mutig oder dumm? Sprich schnell, bevor meine Raptoren Hunger kriegen.",
                      options=[
                          dict(text="Ich will den Bannschlüssel.", cond="quest:q7_pakt=active;!item:ward_key>=1", goto="key"),
                          dict(text="Grukk hat mich geschickt.", cond="flag:grukk_mediated;quest:q7_pakt=active;!item:ward_key>=1", goto="mediated"),
                          dict(text="[Dämonengestalt] KNIE NIEDER.", cond="demon_form;quest:q7_pakt=active;!item:ward_key>=1", goto="demon"),
                          dict(text="Handeln.", action="trade", cond="rep:knochenbrecher>=0"),
                          dict(text="Gehen.", action="end"),
                      ]),
        "key": dict(text="Der Schlüssel? Der ist Skarzas Beute! Was bietest du? Einen Tyrannenzahn und hundert Bernstein – dann reden wir. Oder du forderst mich heraus, wie ein echter Krieger.",
                    options=[
                        dict(text="Hier: Tyrannenzahn und 100 Bernstein.", cond="item:trex_tooth>=1;amber>=100", action="take:trex_tooth:1;amber:-100;give:ward_key:1;rep:knochenbrecher:25;path:protector:1;end"),
                        dict(text="Ich fordere dich heraus!", action="flag:skarza_duel=1;path:conqueror:2;end"),
                        dict(text="Ich komme wieder.", action="end"),
                    ]),
        "mediated": dict(text="Grukk, der alte Ziegendieb … Na gut. Frieden mit den Moosfell ist mehr wert als ein rostiger Schlüssel. Nimm ihn. Aber komm nicht wieder ohne Geschenke.",
                         options=[dict(text="Danke, Skarza.", action="give:ward_key:1;path:protector:2;end")]),
        "demon": dict(text="Bei den Knochen der Ahnen … Der Gehörnte lebt! Skarza dient dir. Nimm den Schlüssel, nimm alles!",
                      options=[dict(text="Gut.", action="give:ward_key:1;rep:knochenbrecher:40;path:demon:2;flag:knochenbrecher_vassal=1;end")]),
    },
    "brannoc": {
        "start": dict(text="Ein Zivilist auf meinem Kap? Ich bin Hauptmann Brannoc Eisenhand. Die Krone will diese Inseln, und ich liefere sie. Bist du nützlich?",
                      options=[
                          dict(text="Ilsa schickt mich wegen des Aschenkamms.", action="advance:q9_aschenkamm", cond="stage:q9_aschenkamm=0", goto="ash"),
                          dict(text="Lehrt mich Schwarzpulver.", action="teach:black_powder", cond="rep:eisenhand>=20"),
                          dict(text="Handeln.", action="trade"),
                          dict(text="Leb wohl.", action="end"),
                      ]),
        "ash": dict(text="Der Vulkan spuckt Wyvern aus. Meine Männer kommen nicht hin – aber ein Bestienbändiger mit Flügeln … Bring mir eine Wyvern, und Eisenhand steht hinter dir. Oder du behältst sie. Dann sind wir Rivalen.",
                    options=[dict(text="Wir werden sehen.", action="end")]),
    },
    "zibbel": {
        "start": dict(text="Mensch! Die Feuerhunde … sind sie weg? Zibbel dachte, Zibbel stirbt im Teer!",
                      options=[dict(text="Du bist sicher. Geh zurück ins Dorf.", action="advance:q4_moosfell;flag:zibbel_saved=1;end", cond="stage:q4_moosfell=2"),
                               dict(text="Geh nach Hause, Zibbel.", action="end")]),
    },
}

DIALOGUES.update({
    "siedler": {"start": dict(text="Ilsa sagt, du kannst mit Bestien umgehen. Halt sie bloß von unseren Ziegen fern.", options=[dict(text="Leb wohl.", action="end")])},
    "siedlerin": {"start": dict(text="Nachts hört man die Feuerhunde heulen. Seit Ewald fort ist, wird es jedes Jahr schlimmer.", options=[dict(text="Ich tue, was ich kann.", action="end")])},
    "moosfell_goblin": {"start": dict(text="Mensch riecht nach Rauch. Grukk sagt, Mensch ist Freund … vielleicht.", options=[dict(text="Gehen.", action="end")])},
    "knochenbrecher_krieger": {"start": dict(text="Skarza ist der Stärkste. Wer stärker ist als Skarza, ist Häuptling. So ist das.", options=[dict(text="Gehen.", action="end")])},
    "soeldner": {"start": dict(text="Der Hauptmann zahlt in Silber, nicht in Bernstein. Noch.", options=[dict(text="Gehen.", action="end")])},
})

# Readable texts (journal pages, inscriptions)
TEXTS = {
    "journal_page_1": "Ewald Varn, Tag 112: Die Inschriften der Alten Warte sprechen von einem „Gehörnten“, der den Vorfahren Kraft gab, als die Bestien übermächtig wurden. Kein Gott – ein Pakt. Ich muss den Schrein im Moor finden.",
    "journal_page_2": "Ewald Varn, Tag 140: Der Schrein ist echt. Die Inschrift verlangt ein schlagendes Herz aus der Tiefe und die Worte der Vorfahren, gesprochen, wenn der Mond am höchsten steht. Ein Herz aus der Tiefe … die Höllenhunde tragen solche Herzen. Ich habe Angst vor dem, was ich vorhabe.",
    "journal_page_3": "Ewald Varn, Tag 151: Ich habe es getan. Der Schrein öffnete mich, und ich wurde … mehr. Ich kann wechseln, wann ich will – Mensch, dann wieder Gehörnter. Aber ich habe den Riss geweckt. Die Stimme will mehr. Wenn jemand dies findet: Wer die drei Seiten kennt, ein Dämonenherz trägt und um Mitternacht am Schrein betet, wird dasselbe erhalten. Möge er stärker sein als ich.",
    "inscription_warte": "„Als die Großen Echsen die Kinder fraßen, gingen die Ahnen zum Gehörnten. Er nahm ihr Blut und gab ihnen Hörner.“",
    "inscription_schrein": "„Ein Herz, das schlägt, wo keines schlagen sollte. Drei Worte, die drei Seiten bergen. Die Stunde, in der der Mond über dem Moor steht.“",
}
